### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by havatv**
Another image for the processing modeller canvas (#1603).

### CODE REVIEW

**Comment by DelazJ** [comment]
@havatv there's an issue with this commit. the image is not the right one. https://docs.qgis.org/testing/en/docs/user_manual/processing/modeler.html#definition-of-the-workflow

**Comment by havatv** [comment]
Very sorry about that! I will fix asap.
Thank you so much for checking!

**Comment by havatv** [comment]
Hopefully fixed now (direct commit - e587cc9d10dcbae55034384603d11f6db8e3a829)

**Comment by DelazJ** [comment]
It's. Thanks

**Pull request merged**
