### PR TITLE
Cleaning figure numbering and title

### PR DESCRIPTION
**Pull request by DelazJ**
Related discussion: http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-Issues-with-figure-numerotation-cleanup-td5291754.html
Related issues: #788
This PR:
- removes the numbered title shown in html at the top of most of the images; it appears that the [Metasearch chapter](http://docs.qgis.org/testing/en/docs/user_manual/plugins/plugins_metasearch.html) is already like this.
- renames the hyperlink reference to these figures (instead of removing): no more numbering, but an unique name that refers as far as possible to the figure caption (will ease pdf reading for some chapters). Now that all figures are referenced, I wonder if it would improve the doc reading to add those `(see figure_...)` in the text. The [gentle gis doc](http://docs.qgis.org/testing/en/docs/gentle_gis_introduction/introducing_gis.html) is written like that (indicate the figure corresponding to the current comment).
- also rename some table's reference (table often do not have caption so few are concerned). 
- add, rename, move or remove some indices. Let's see how the index table looks like.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
@DelazJ @yjacolin I've already been experimenting with Python3/newest sphinx too. We could move to it I think, I 'only' have to create new Docker images for this. Or did one of you see problems?

**Comment by DelazJ** [comment]
@rduivenvoorde If the experimentation was successful, no objection from me. Let's upgrade stuffs

**Comment by yjacolin** [comment]
I don't remember any issue on my side with my test. So +1

**Comment by DelazJ** [comment]
Let's begin the move to a new "level". Merging!

**Pull request merged**
