### PR TITLE
Clean project instance

### PR DESCRIPTION
**Pull request by SrNetoChan**
This aims to fix the problem of doctests using objects from tests in other rst files.

### Description

Goal:

Ticket: #

- [ ] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [ ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ ] This PR passes the checks.

### CODE REVIEW

**Comment by DelazJ** [comment]
Let's see

**Comment by DelazJ** [comment]
@SrNetoChan the repository (master) is green. Thanks. I'm rebasing @havatv PR and let's see if they succeed too.
In the list i mention some global options: [doctest_global_setup](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#confval-doctest_global_setup) and its cleanup version. Should we not use one of them if we have to separate tests file by file or group by group?

**Comment by SrNetoChan** [comment]
Yes, that's probably a better option. I will try to make a PR for that later, and see if it works.

**Comment by ghtmtt** [comment]
Thanks @SrNetoChan for the fix!

**Pull request merged**
