### PR TITLE
Introduce ArcGIS Rest Servers entry

### LINKED ISSUE #6381: Remove seperation between ArcGis Feature Service and ArcGIS Map Service items in browser (Request in QGIS)
### Request for documentation
From pull request QGIS/qgis#40700
Author: @nyalldawson
QGIS version: 3.18

**Remove seperation between ArcGis Feature Service and ArcGIS Map Service items in browser**

### PR Description:
Builds off https://github.com/qgis/QGIS/pull/40697:

Replaces the separate "ArcGis Feature Service" and "ArcGIS Map Service" browser items/connections with a single, unified "ArcGIS Rest Servers" connection and browser node which shows a definitive view of the server exposing both service types.

This makes it MUCH easier to manage and browse these servers, and matches user instead of the awkward forced separation between the layer types.

### Commits tagged with [need-docs] or [FEATURE]
"\n\n\n\n Remove seperation between ArcGis Feature Service\nand ArcGIS Map Service items in browser\n\nand replace them with a single, unified \"ArcGIS Rest Servers\" item\nwhich shows a definitive view of the server exposing both\nservice types."

### PR DESCRIPTION
**Pull request by mizmay**
Adds a section to Introduction / Browser Panel to describe "ArcGIS Rest Servers" to fix #6381.

Still to do / potentially as part of this fix:
- replace screenshot (shows separate entries for "ArcGIS Feature Services" and "ArcGIS Map Services"
- add additional info about: connecting to ArcGIS server, differences between adding a feature service vs a map service if any, options once connection is created

Other pages that mention ArcGIS Feature Services or ArcGIS Map Services, but at current level of detail don't seem worth updating:
docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
docs/user_manual/introduction/qgis_gui.rst

This is my first PR to this project, fair to assume I don't know anything, thanks and 👋 !

### CODE REVIEW

**Comment by DelazJ** [comment]
@mizmay I think you are on the right track (_and if ever you need help, do not hesitate to ask_)
> Still to do / potentially as part of this fix:
>
> -   replace screenshot (shows separate entries for "ArcGIS Feature Services" and "ArcGIS Map Services"
> -  add additional info about: connecting to ArcGIS server, differences between adding a feature service vs a map service if any, options once connection is created

Very welcome :+1: 
> Other pages that mention ArcGIS Feature Services or ArcGIS Map Services, but at current level of detail don't seem worth updating:
docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
docs/user_manual/introduction/qgis_gui.rst

IMHO better update the references. And at least the latter will change since the buttons should not exist anymore (see https://github.com/qgis/QGIS/pull/41238)
Thanks.

**Comment by mizmay** [comment]
Thanks for commenting @DelazJ! 

What's the recommended flow for building/maintaining the not-yet-released version of QGIS? I would need to do this in order to update the screenshots.

**Comment by DelazJ** [comment]
It depends on your OS but generally speaking, you don't need to build QGIS if it's just about contributing to documentation. QGIS project already provides nightly builds of the development version you can grab for main platforms. For example,
- if you are on windows, you check qgis-dev while installing through osgeo4w advanced install (https://qgis.org/en/site/forusers/alldownloads.html#windows) -- you'd need to regularly run the setup file to have the latest version
- if on macOS, you might have https://qgis.org/en/site/forusers/alldownloads.html#qgis-nightly-release
- if on Debian/Ubuntu, use the associated repo (https://qgis.org/en/site/forusers/alldownloads.html#repositories). I think, in this case, only one version can be installed so if you want to keep 3.16 or 3.10 aside, you'd need to rely on alternate install such as [flatpak](https://qgis.org/en/site/forusers/alldownloads.html#flatpak) but I'm less aware of how the update is handled.

But if you really want to build, you'll find instructions in the [code repo](https://github.com/qgis/QGIS/blob/master/INSTALL.md)

**Comment by mizmay** [comment]
This is now parity with what the documentation was for ArcGIS Map/Feature Services - e.g. there really is none. I am pretty ignorant of ArcGIS Portals and what any of these fields mean; if @nyalldawson or anyone else has bandwidth to walk me through an example I'm happy to write it up/add it to the PR, but I think the critical updates are addressed here already.

Can also file a task to address the lack of documentation on ArcGIS services <-> QGIS at another time.

**Comment by DelazJ** [comment]
Thanks @mizmay.
> Can also file a task to address the lack of documentation on ArcGIS services <-> QGIS at another time.

I think there are already tickets. But let's merge this PR and do the fix in another round.

**Pull request merged**
