### PR TITLE
Minor language corrections/improvements

### PR DESCRIPTION
**Pull request by tomchadwin**
General Tools (https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html)

Complete to l1071, before "Measuring"

### CODE REVIEW

**Comment by havatv** [comment]
@tomchadwin, with this pull request, you are undoing the changes from one of your merged pull request (#3390).  A git issue?

**Comment by tomchadwin** [comment]
@havatv Arg! You're right. Only the change from L783 should have been in this PR. Umm, I'll see if I can figure how to rectify after lunch. Help welcome...

**Comment by DelazJ** [comment]
@tomchadwin If you want to do a web-only fix, open the file in [qgis:master branch](https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/introduction/general_tools.rst) and copy lines 1 to 782 and replace them in your [patch-1 branch](https://github.com/tomchadwin/QGIS-Documentation/blob/patch-1/source/docs/user_manual/introduction/general_tools.rst) and commit.

Btw, thanks to you two for all the hard work and the dynamism you are putting in this repository. Glad to see that.

**Comment by tomchadwin** [comment]
That's fixed it, I think. Thanks, @DelazJ! Apologies for making a mess of the commits. Not sure I quite see how to avoid making the same mistake again under the same circumstances, but sure I'll figure it out in time.

**Comment by havatv** [comment]
Thanks again, @tomchadwin !

**Pull request merged**
