### PR TITLE
Travis doctest docker

### PR DESCRIPTION
**Pull request by arnaud-morvan**
### Description

Goal:

Ticket: #

- [ ] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [ ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ ] This PR passes the checks.

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@SrNetoChan : I've finished you PR on running doctest in Travis.

**Comment by SrNetoChan** [comment]
Oh great! Thanks!

**Comment by SrNetoChan** [comment]
@ghtmtt @rduivenvoorde should we?

**Comment by ghtmtt** [comment]
I don't see any reason why not merge this awesome new enhancement :)

**Comment by ghtmtt** [comment]
that's really cool @arnaud-morvan, thanks!

**Comment by DelazJ** [comment]
@arnaud-morvan i guess this has to be backported, too.

**Pull request merged**
