### PR TITLE
Add tag for plugins supporting Qt6

### PR DESCRIPTION
**Pull request by DelazJ**
I think I read something about this few weeks ago...
@rduivenvoorde @nyalldawson @troopa81 Is this OK?

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Yep looks good to me. I see in my plugin I use 'yes' instead of 'True', apparently both are valid?

**Comment by troopa81** [comment]
Looks good to me to!

**Comment by DelazJ** [comment]
> I see in my plugin I use 'yes' instead of 'True', apparently both are valid?

No strong idea 😄 but I think there used to be this double usage of boolean in this file. No idea how I could verify this, but as most of the boolean tags in the sample here were using True/False I opted for consistency.

**Comment by rduivenvoorde** [comment]
FYI: I created an issue to add this tag to the plugins.xml:  https://github.com/qgis/QGIS-Django/issues/373

**Comment by elpaso** [comment]
@rduivenvoorde wouldn't be more future proof if we used `minQtVersion/maxQtVersion`  (both defaulting to 5 for now) ?

**Comment by DelazJ** [comment]
So, verdict: `supportsQt6` or `minQtVersion/maxQtVersion`?

**Comment by rduivenvoorde** [comment]
@DelazJ I like @elpaso 's proposal, though it would probably need some small changes in core then.
@nyalldawson do you have a strong opinion on this?

**Comment by DelazJ** [comment]
OK let's then close and wait for the min/max options. Might be a worth an issue report in code repo?

**Pull request closed without merging**
