### PR TITLE
Add few example to expression functions

### LINKED ISSUE #700: Add few example to expression functions
It'd be nice to have few examples of expression for each group of functions in http://docs.qgis.org/2.8/en/docs/user_manual/working_with_vector/expression.html

### PR DESCRIPTION
**Pull request by yjacolin**
Fix #700

### CODE REVIEW

**Comment by yjacolin** [comment]
@DelazJ @SrNetoChan could you confirm that it is ok for you. Is so we can add more and more examples. In long terme, we should split the files in three differents files.

**Comment by SrNetoChan** [comment]
I think it would be better if the expression examples are after each expression groups. As we did with datetime expressions before (not sure if it was merged already)

**Comment by yjacolin** [comment]
ah ok didn't see the examples below the table :( I move some of my example and remove other that already exists.

**Comment by DelazJ** [comment]
LGTM

**Comment by yjacolin** [comment]
@delaz could you approve the PR with the official button :) Doing this way we can see it in the PR index page easily!

**Pull request merged**
