### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by ka1bi4**
Hello! I fixed some spelling mistakes.

Goal:

Ticket(s): #

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@ka1bi4 it seems you have edited an old version of the docs and there are some conflicts now. Can you resolve the conflicts? or you prefer me to do it?

**Comment by SrNetoChan** [comment]
BTW, for your own good, next time, create a new branch before you edit the files. If you used the command line:

git checkout -b <new_branch_name>

If you used the github web editor, always choose to create a new branch.

 This way your master branch is always clean and can be always updated from the upstream (QGIS/QGIS Documentation) repository.

**Comment by ka1bi4** [comment]
Sorry, I was a bit rash. Well, I shall try to do better next time.

**Comment by SrNetoChan** [comment]
oh... @ka1bi4  no need to redo it! we could have fixed it in here. Are you going to prepare another PR?

**Comment by ka1bi4** [comment]
> oh... @ka1bi4 no need to redo it! we could have fixed it in here. Are you going to prepare another PR?

Oops, I opened a new Pull Request

**Comment by DelazJ** [comment]
Looking at the branches, changes here are not available in the other PR. I propose to reopen this one, fix the conflict (Alex, can you handle that, please?), merge and show you how to update your master branch (for reference we have some literature at https://docs.qgis.org/testing/en/docs/documentation_guidelines/first_contribution.html#for-testing-doc-master-branch)

**Pull request closed without merging**
