### PR TITLE
Add GeoPackage Chapter to Vector supported data

### PR DESCRIPTION
**Pull request by juliecodina**
to be improved

### CODE REVIEW

**Comment by havatv** [comment]
@juliecodina, are you waiting for this to be merged, or are you planning toadd more commits here?

**Comment by DelazJ** [comment]
@juliecodina any plans on this?

**Comment by DelazJ** [comment]
@juliecodina I suggest we close this for the moment and reopen when there's more description. Merci.

**Comment by juliecodina** [comment]
I'm sorry, I didn't see your mails. I created this commit during a QGIS
workshop.
I was learning how to contribute.
I don't have the time now to continue this commit.
I'm sorry for the time you take with it.
Julie

**Comment by DelazJ** [comment]
No problem. Feel free to come back when you want/can.

**Pull request closed without merging**
