### PR TITLE
Restructured labelling section

### PR DESCRIPTION
**Pull request by sokolic**
Restructured labelling section to better reflect work flow.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
huh... 880 files changing?

is this going ok?

**Comment by sokolic** [comment]
Not sure why it says 880 changing. I only changed one file.

**Comment by rduivenvoorde** [comment]
@sokolic only vector_properties.rst ?

Because better I think we can pull that in then by hand

**Comment by sokolic** [comment]
Yes, I only changed vector_properties.rst.

**Comment by rduivenvoorde** [comment]
ok, just to be sure, can you have a look into this:

https://raw.githubusercontent.com/qgis/QGIS-Documentation/5e9e7a13cbcd7d066e245c43572f6ac9bfac2f59/source/docs/user_manual/working_with_vector/vector_properties.rst

does that contain your fixes? If so I'll commit locally here, as to be honest I do not know how to only pull your commit in master now... :-(    (or tell me if you know)

**Comment by sokolic** [comment]
Yes, that file contains my changes. I'm still quite new to doing documentation with GitHub so don't know why this affected all those other files. Maybe I made changes to an old branch?

**Comment by m-kuhn** [comment]
@sokolic if you look on top, this pr

> wants to merge 210 commits into qgis:patch-1 from sokolic:patch-1

the target should be qgis:master and not qgis:patch-1. Best to restart with a new pull request and chose the proper base branch.

**Comment by sokolic** [comment]
Ok, let me try that.

**Comment by rduivenvoorde** [comment]
Thanks @m-kuhn. 

I already took the one file and added it by hand as part of another cleanup I mentioned because I looked into this one...
Tested and builds fine.
So will close this one

**Pull request closed without merging**
