### PR TITLE
Update vector_properties.rst

### PR DESCRIPTION
**Pull request by mezwor**
Updated the metadata menu section with some contents

### CODE REVIEW

**Comment by yjacolin** [comment]
Why did you close your PR? Looks good to me.

**Comment by mezwor** [comment]
I have been trying to fix the following error:
"This branch has conflicts that must be resolved" But failed and I am trying again

**Comment by yjacolin** [comment]
The good point here is that you worked on a custom branch in your repository and create a PR towards master.

The wrong point is probably that the master branch in your repository from which you create your branch was not uptodate. You can try this:
```
git checkout mezwor-update-manual-2.14 (you should already be there)
git fetch upstream (do you have upstream remote in your local clone?)
git rebase upstream/master
git push -force origin mezwor-update-manual-2.14
```
You will have probably some conflict to correct.

and compare your branch in front of

**Comment by DelazJ** [comment]
To complete @yjacolin comment you'll find at http://qgis.org/fr/site/getinvolved/development/qgisdevelopersguide/git.html#submitting-patches-and-pull-requests few instructions about using git in QGIS environment that may help you (the chapter is for QGIS application but I think you'll easily do the parallel)

**Comment by mezwor** [comment]
okay thanks let me follow your recommendations

**Comment by DelazJ** [comment]
replaced by #817

**Pull request closed without merging**
