### PR TITLE
Adding missing exercise data for the forestry module

### PR DESCRIPTION
**Pull request by sn1054**
This files were missing from the forestry module data and I created a similar one that can be used for the exercises.

### CODE REVIEW

**Comment by elpaso** [comment]
Thank you!

This closes #500 but before merging  could you please make sure that in the training manual there is a link to this files so that the readers can find them? Sorry but I'm not familiar with that part of the manual.

**Comment by sn1054** [comment]
Well, the main and first part of the Training Manual directs you to download the exercise_data from this link: http://qgis.org/downloads/data/training_manual_exercise_data.zip 

But the Forestry Application Module has a separate data set that (as stated in the manual) is available on Dropbox:
https://dl.dropboxusercontent.com/u/3200993/forestry_data.zip
So the forest_stands_2012 should actually be in this zip file in Dropbox.

Anyway, since this forestry_data doesn't seem to be on github, i added my files to exercise_data here in the repository instead.
Ideally, tho, whole forestry zip that is on dropbox could be included here in the exercise_data so everything is in one place. I can do that if you like. Then the link to dropbox can be erased from the training manual.

And about the link at the beginning of the manual (http://qgis.org/downloads/data/training_manual_exercise_data.zip ), it doesnt seem to get the data from github but from sth i have no access to. Maybe it would be interesting to change the link on the manual to get the data from github instead.

So, let me know what you would like to do and if I can help with anything.
Have a great weekend :)

**Comment by elpaso** [comment]
Thanks!
I think you can ask Larissa @junek and Otto @dassau  what is the best thing to do, I also suggest to avoid dropbox or other external storage and keep everything in one place.

**Comment by rduivenvoorde** [comment]
see https://github.com/qgis/QGIS-Documentation/issues/500

**Pull request closed without merging**
