### PR TITLE
Update reference to QGIS

### PR DESCRIPTION
**Pull request by dragons8mycat**
Review document and update reference to [qg] as QGIS

### CODE REVIEW

**Comment by yjacolin** [comment]
|qg| is a sphinx shorcut for QGIS, why do you want to change it?

And your branch has now a conflicts with master.

**Comment by yjacolin** [comment]
Hum it seems that the sentenced has been rephrased see http://docs.qgis.org/2.8/en/docs/user_manual/working_with_vector/expression.html

**Comment by DelazJ** [comment]
@yjacolin wrote:
> |qg| is a sphinx shorcut for QGIS, why do you want to change it?

In this [thread](http://lists.osgeo.org/pipermail/qgis-community-team/2016-January/004412.html) it has somehow been decided to get rid of most of the unneeded substitutions used in the doc (cost build time), including |qg|
>Hum it seems that the sentenced has been rephrased see http://docs.qgis.org/2.8/en/docs/user_manual/working_with_vector/expression.html

It's rather http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html. However, can someone explain me why this PR has conflicts against master?

**Comment by rduivenvoorde** [comment]
Sorry guys, I have been messing up recently with my quest to make stuff github editable.

Feel free to roll back all my edits, or I will try to do it myself in near future.

I think I only messed up the vector_properties.rst in working_with_vector. And the images directory in that dir. Which has had some newer screenshots after I added it... So these screenshots should go to the resource/en directory again...

What is the preference? Should I dig up an old version of the vector_properties.rst (but then probably throwing away some work of others), or can we do something more clever here?
The images-directory should probably copied over de old images, so the newer ones will be in their original places, and the images directory is to be remove.

**Comment by dragons8mycat** [comment]
Apologies @yjacolin, I was just going through reviewing and some of the other documentation referred to "QGIS" rather than [qg]. I followed this thread by Diethard: https://lists.osgeo.org/pipermail/qgis-community-team/2016-January/004412.html where it was suggested QGIS was used.

**Comment by DelazJ** [comment]
@rduivenvoorde I moved your comment to #793  and replied to it there as you already began such a discussion there.

**Comment by yjacolin** [comment]
Sorry @dragons8mycat could you close this PR and send a new one?

**Pull request closed without merging**
