### PR TITLE
Add a link to the documentation index in the documentation sidebar

### LINKED ISSUE #5543: Give the index a promenent place on the docs web pages
## Description

The documentation index covers all the documentation, and can be very useful when searching the documentation for specific features. We have an index (https://docs.qgis.org/3.10/en/genindex.html), but it is hard to find.

1. Let us say that we start with the documentation page https://www.qgis.org/en/docs/index.html
    No trace of the index can be found there.
2. So we try the link to the 3.10 User guide, but nothing there either - the same with all the other links under 3.10 (and 3.4 and "testing").
3. From the 3.10 User guide, if we choose the "Previous" button on the top left, we arrive at https://docs.qgis.org/3.10/en/docs/index.html
4. Searching for "index" leads us to a "section" under Training Manual called "Indices and tables" (https://docs.qgis.org/3.10/en/docs/training_manual/index.html#indices-and-tables)
5. From there there is a link to "Index" (https://docs.qgis.org/3.10/en/genindex.html) - and we have arrived!

The index is too well hidden - the index should be available from the "permanent" left-hand pane of the documentation, for instance directly below the "Search docs" field in the blue area or at the bottom of the black area below.

Page URL: https://www.qgis.org/en/docs, https://docs.qgis.org/testing/en/docs/index.html, https://docs.qgis.org/3.10/en/genindex.html

### PR DESCRIPTION
**Pull request by havatv**
Goal: Add a link to the documentation index in the documentation sidebar. The link is placed at the bottom of the sidebar title (under the "search the docs" field).

Ticket(s): Fix #5543

- [x] Backport to LTR documentation is required

### CODE REVIEW

**Comment by DelazJ** [comment]
Mind sharing a screenshot?

**Comment by havatv** [comment]
> Mind sharing a screenshot? Thanks

image

**Comment by SrNetoChan** [comment]
I can see how useful the index can be, but I wonder if this is the best place to put it... Besides, the term index is not clear to me that it won't go the documents index and not a list of terms.

**Comment by ghtmtt** [comment]
related to adding new buttons in the sidebar. Especially in the pyqgis docs a `Go to Top` in the lower part of the sidebar would be ultra-useful. :)

**Comment by havatv** [comment]
> I can see how useful the index can be, but I wonder if this is the best place to put it... Besides, the term index is not clear to me that it won't go the documents index and not a list of terms.

It is important that the link to the index always is available and visible, preferably at the same location in the "UI". The top of the left panel is such a place.

If you are aware of another term, please let me know. **Index** is the term normally used in books (https://www.google.com/search?q=book+index), and also quite commonly used for all kinds of documents (https://www.google.com/search?q=document+index).

**Pull request merged**
