### PR TITLE
PyQGIS Developer Cookbook: fix qgis_global_settings.ini file name

### PR DESCRIPTION
**Pull request by agiudiceandrea**
Goal: fixes the global settings filename. @elpaso could you please have a look?

Ticket(s): #

- [x] Backport to LTR documentation is requested

### CODE REVIEW

**Comment by DelazJ** [comment]
@elpaso Good to merge? Thanks.

**Comment by DelazJ** [comment]
@agiudiceandrea if you are confident enough with this, I am OK to merge...

**Comment by agiudiceandrea** [comment]
I think, quite enough. See also: https://github.com/qgis/QGIS/pull/55428.

**Comment by DelazJ** [comment]
Yep, I saw it but wanted your confirmation anyway 😄

**Pull request merged**
