### PR TITLE
Backport to 3.4 of table formatting for alg parameters for QGIS vector geometry algs

### PR DESCRIPTION
**Pull request by havatv**
Goal:

Ticket(s): #

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by DelazJ** [comment]
For the missing image, i think there's still an issue with it: can't get a preview of it, and this is something I came across today https://github.com/qgis/QGIS-Documentation/compare/havatv-bp34-tableforalgs_qgisvectgeom...DelazJ:algBrokenImages

**Comment by havatv** [comment]
> For the missing image, i think there's still an issue with it: can't get a preview of it, and this is something I came across today [havatv-bp34-tableforalgs_qgisvectgeom...DelazJ:algBrokenImages](https://github.com/qgis/QGIS-Documentation/compare/havatv-bp34-tableforalgs_qgisvectgeom...DelazJ:algBrokenImages)

When backporting, I included the recently added documentation of the validation checks, and that is the reason for the missing images. Let's see if I have found all of them now... :-)

**Comment by DelazJ** [comment]
Issue is that, the files are there but these are broken files: they do not render as png, neither in github nor html. And my branch addresses old files in the 3.4 branch not the missing ones you are backporting

**Comment by havatv** [comment]
> Issue is that, the files are there but these are broken files: they do not render as png, neither in github nor html. And my branch addresses old files in the 3.4 branch not the missing ones you are backporting

In "my" case, the files are there in master, but not in 3.4.  They have never been backported to 3.4, so that is not unexpected.

**Comment by DelazJ** [comment]
Well let's say it in another way: go to the [3.4 branch](https://github.com/qgis/QGIS-Documentation/tree/release_3.4/source/docs/user_manual/processing_algs/qgis/img) and see how the images look like, both the two you committed right now and the ones I'm updating

**Comment by havatv** [comment]
> Well let's say it in another way: go to the [3.4 branch](https://github.com/qgis/QGIS-Documentation/tree/release_3.4/source/docs/user_manual/processing_algs/qgis/img) and see how the images look like, both the two you committed right now and the ones I'm updating

Now I see the problem, yes.  This did not cause any problems with travis, that was why I did not notice.

**Comment by DelazJ** [comment]
> Now I see the problem, yes. This did not cause any problems with travis, that was why I did not notice.

Yep, travis is not infallible
I think you also miss "delete holes" and "drop z/m values" for those I've noticed before you incrementally fix the copy-paste errors

**Comment by havatv** [comment]
> I think you also miss "delete holes" and "drop z/m values" for those I've noticed before you incrementally fix the copy-paste errors

I think I have managed to find all the cut and paste errors now.
The problem was that when cutting, not all the selected text was included...

**Pull request merged**
