### PR TITLE
Sort algorithms order

### PR DESCRIPTION
**Pull request by DelazJ**
and fix misc details

Goal:

Ticket(s): #

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by havatv** [comment]
Can I check if this collides with one of my PRs before we merge?

**Comment by DelazJ** [comment]
Of course. No hurry.

**Comment by havatv** [comment]
@DelazJ, this may break my big #4428 PR.  Is it OK that I include your fixes in #4428 to avoid possible problems, and then close this one?

**Comment by havatv** [comment]
I have now included your fixes into #4428. I have tried to implement all the changes you proposed in this PR.

**Comment by DelazJ** [comment]
Not fully:
- the title has an uppercase letter only for the first letter: "Overlap analysis" instead of "Overlap Analysis"
- description does not begin with "this algorithm...."

These make it inline with other algs

**Comment by havatv** [comment]
> Not fully:
> 
>     * the title has an uppercase letter only for the first letter: "Overlap analysis" instead of "Overlap Analysis"
> 
>     * description does not begin with "this algorithm...."
> 
> 
> These make it inline with other algs

Thanks! Fixed!

**Comment by DelazJ** [comment]
Closing then

**Pull request closed without merging**
