### PR TITLE
Add doc for dynamic forms and editable join options

### LINKED ISSUE #1977: [FEATURE] Dynamic form for joined fields
Original commit: https://github.com/qgis/QGIS/commit/632eca60793ec6a43967935c66c6f76dcec48cc8 by web-flow

[FEATURE] Dynamic form for joined fields

### LINKED ISSUE #2005: [FEATURE] Constraints are updated on joined fields when dynamic form option is enabled
Original commit: https://github.com/qgis/QGIS/commit/1811a396541f498d0ddf66550118543a36709f62 by pblottiere

Unfortunately this naughty coder did not write a description... :-(

### LINKED ISSUE #2006: [FEATURE] Constraints are resolved for joined fields
Original commit: https://github.com/qgis/QGIS/commit/1b9c5be10d4733852cf2c5c843252bbf17306675 by web-flow

[FEATURE] Constraints are resolved for joined fields

### LINKED ISSUE #2061: [FEATURE] Joined fields are editable if the option is activated
Original commit: https://github.com/qgis/QGIS/commit/477775a5d7998aa20672a64f5ec62ca6e5793595 by pblottiere

Unfortunately this naughty coder did not write a description... :-(

### LINKED ISSUE #2062: [FEATURE] Joined layers are editable
Original commit: https://github.com/qgis/QGIS/commit/30b46f7617cbbbe88ff0b4d049e1845fe937daab by web-flow

[FEATURE] Joined layers are editable

### PR DESCRIPTION
**Pull request by pblottiere**
Add a little paragraph for join configuration about:

- Dynamic form 
- Editable joins

Fix #2062 
Fix #2061 
Fix #2006 
Fix #2005 
Fix #1977

### CODE REVIEW

**Comment by pblottiere** [comment]
@DelazJ thank you for your review! I took into account you comments and I added a sentence about the  "cache join layer in virtual memory" option.

However, I don't have a clue about the FIXME:

```
.. FIXME: are table joins also possible with MSSQL and ORACLE tables?
```

@m-kuhn, do you have an answer about this comment in the documentation?

**Comment by m-kuhn** [comment]
As far as I know joins are completely done on client (QGIS) side, so it doesn't matter which provider sits behind.

**Comment by pblottiere** [comment]
> As far as I know joins are completely done on client (QGIS) side, so it doesn't matter which provider sits behind.

Thank you for your quick answer Matthias!

@DelazJ I think I can remove this FIXME, do you agree?

**Comment by DelazJ** [comment]
Yes, please

**Comment by pblottiere** [comment]
Done.

**Comment by pblottiere** [comment]
@DelazJ Do you want me to update something to merge this PR?

**Comment by DelazJ** [comment]
Hum...not really... Let's merge and see if clarification are needed.
Thanks

**Pull request merged**
