### PR TITLE
Fix labels backgroundsetting marker

### PR DESCRIPTION
**Pull request by lajunek**
Goal: use the correct typo

Ticket(s): #

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by DelazJ** [comment]
@lajunek please see #4697.

**Comment by havatv** [comment]
Sorry, @DelazJ, I did not see you comment before merging.

**Comment by lajunek** [comment]
@DelazJ I see there are conflicts now because I didn't consider #4697.

**Comment by DelazJ** [comment]
#4687 was pushed and merged without review, resulting in the text not being in the right section and not addressing the right setting (mentions buffer instead of background). So while #4697 is (re)moving that paragraph, you were updating it ==> the conflict is unavoidable. Anyways, it's too late now, so I rebased and fixed the conflict.

**Pull request merged**
