### PR TITLE
use qgis namespace to import processing fix #3600

### LINKED ISSUE #3600: [needs-docs][processing] Monkey patch stable external Processing API into qgis.processing
Original commit: https://github.com/qgis/QGIS/commit/64387a2254835bb1f91fbbd23f39720ea0c4b4ec by nyalldawson

Instead of encouraging use of the internal Processing modules
(e.g. from processing.tools.general import run , import processing, ...)
instead expose all Python specific STABLE processing additions
to the qgis.processing module.

Instead, scripts and plugins should now use

from qgis.processing import run, algorithmHelp,...

This makes a clear distinction between internal Processing python
modules (i.e., everything else!) and the parts of Processing
which are stable and designed to be used by plugins and scripts.

TODO: QGIS 4.0 -- move the internal Processing plugin modules
to __processing, to clearer indicate that this is all internal
stuff.

### PR DESCRIPTION
**Pull request by Gustry**
### Description

Goal: use qgis namespace to import processing

Ticket: #3600 

- [ ] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [ ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ ] This PR passes the checks.

### CODE REVIEW

**Comment by DelazJ** [comment]
Is this ready to merge @Gustry ?

**Comment by Gustry** [comment]
@DelazJ Yes, it is. Please use the squash button.

Where should I open an issue about the PyQGIS API doc? https://qgis.org/pyqgis/master/
It would be nice to display in the documentation: https://github.com/qgis/QGIS/commit/64387a2254835bb1f91fbbd23f39720ea0c4b4ec
But these are monkey patching, so not so easy I guess. @3nids Any idea?

**Comment by DelazJ** [comment]
> Where should I open an issue about the PyQGIS API doc? https://qgis.org/pyqgis/master/

https://github.com/qgis/pyqgis/issues

**Comment by Gustry** [comment]
Thanks, I didn't know this repository.

**Comment by DelazJ** [comment]
> Thanks, I didn't know this repository.

If I may, you are not alone. I had to look for it in the past and had redirected people reporting issue here also. It could be nice that https://github.com/qgis/pyqgis/issues/19 get solved.

**Pull request merged**
