### PR TITLE
Workaround segfault in auth manager test code

### LINKED ISSUE #5398: [doctest] Segmentation fault (core dumped) make builds fail randomly
Some PRs (https://travis-ci.org/github/qgis/QGIS-Documentation/pull_requests) are failing for the following reason (and this does not happen systematically)
```
Document: docs/user_manual/auth_system/auth_workflows
-----------------------------------------------------
Makefile:43: recipe for target 'doctest' failed
make: *** [doctest] Segmentation fault (core dumped)
docker.mk:4: recipe for target 'doctest' failed
make: *** [doctest] Error 2
The command "make -f docker.mk doctest" exited with 2.
cache.2
store build cache
```
Anyone knows what the issue could be?

### PR DESCRIPTION
**Pull request by elpaso**
I've run the test through debugger but I couldn't make it fail, it's threaded code so I guess that the random failure is just a false positive, I couldn't find a better solution than disabling the test.

Fixes #5398

### CODE REVIEW

**Comment by DelazJ** [comment]
@elpaso Thanks but unfortunately, the failure has moved to another row (https://travis-ci.org/github/qgis/QGIS-Documentation/builds/692927352 for #5581 - the branch includes this change afaics)

**Comment by havatv** [comment]
docs/pyqgis_developer_cookbook/loadproject.rst contains the code:

    .. testcode:: loadproject

    # If you are not inside a QGIS console you first need to import
    # qgis and PyQt classes you will use in this script as shown below:
    from qgis.core import QgsProject
    # Get the project instance
    project = QgsProject.instance()
    # Print the current project file name (might be empty in case no projects have been loaded)
    # print(project.fileName())

    # Load another project
    project.read('testdata/01_project.qgs')
    print(project.fileName())

    .. testoutput:: loadproject

    testdata/01_project.qgs

I can't find `testdata/01_project.qgs` anywhere - could that be the cause of this?

**Comment by DelazJ** [comment]
> I can't find testdata/01_project.qgs anywhere - could that be the cause of this?

https://github.com/qgis/QGIS-Documentation/blob/master/conf.py#L226

**Comment by DelazJ** [comment]
Actually things are getting worse and I'm getting crazy with all those red crosses. Not a single PR has passed for days in master; committing, restarting brought no change. I've made a branch reverting this PR but it's also failing in my fork and restarting the build has no effect, unlike when I raised the issue.
Could the issue be in the docker file (I don't know what I'm talking about) or in the project files themselves? The `Logged warning: Duplicate provider native registered` stops the build in the loadproject tests but it is raised right after the code testing begins.
@elpaso should I make another call to devs list or do you think you could give it a look again.

I'll be merging PRs that have no other issue in the meantime.

**Pull request merged**
