### PR TITLE
Document Shape Digitizing tools

### LINKED ISSUE #2179: [FEATURE][needs-docs] Add gui to draw Circle, Ellipse, Rectangle and Regular Polygon
Original commit: https://github.com/qgis/QGIS/commit/a48c2e8fd445d7d94b58f0434ba01a2b6a44a0d2 by web-flow

[FEATURE][needs-docs] Add gui to draw Circle, Ellipse, Rectangle and Regular Polygon

### LINKED ISSUE #3172: [FEATURE][needs-docs]Add map tool: rectangle 3 points (projected)
Original commit: https://github.com/qgis/QGIS/commit/b089b576810207f1dd2d2513a966a32f21ad91f6 by web-flow

[FEATURE][needs-docs]Add map tool: rectangle 3 points (projected)

### LINKED ISSUE #4038: Documentation for shape toolbar
## Description

@SrNetoChan @pigreco 
To do with our discussion on twitter, here some information about all tools in the shape toolbar.

There is a [section](https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst#shape-digitizing) about it, containing only an information for circular string / arc.

For every tool, you can enter coordinate with The Advanced Digitizing panel.

## Circle:

Circles are converted to circular string, so it can be in curved geometry or not depending of the data provider.

- **Circle from 2 points**: Points define the diameter and the orientation of the circle. / Left click, right click.[QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/Circle2P/doc/Circle2P_en.html)
- **Circle from 3 points**: Draws a circle from three known points on the circle. / Left click, left click, right click.[QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/Circle3P/doc/Circle3P_en.html)
- **Circle from center and a point**: Draws a circle with a given center and a point on the circle. With advanced digitizing panel can be "center and a radius" using the distance tool  / Left click, right click. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/CircleCP/doc/CircleCP_en.html)
- **Circle from 3 tangents**: Draws a circle that is tangential to three entities. **You have to activate snapping segment.** Obviously, you must click on a segment to add a tangent. If two tangents are parallels a message appear and clear input. <-- but I don't remember why I did that... bug report https://github.com/qgis/QGIS/issues/30933  / Left click (on a segment), left click (on a segment), right click (on a segment).[QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/Circle3T/doc/Circle3T_en.html)
- **Circle from 2 tangents and a point**: As circle from 3 tangents, except that you have to select to tangents, enter a radius and select the center. This tool is the same as QCad and not as AutoCAD. https://twitter.com/lo_bartoletti/status/1154278602046943233   / Left click (on a segment), left click (on a segment), right click. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/Circle2TR/doc/Circle2TR_en.html)

## Ellipse:

Ellipse cannot be converted as circular string, so it will always segmented.

- **Ellipse from center and two points**: Draws ellipses with a given center, major axis and minor axis.   / Left click, left click, right click. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Ellipse/EllipseCPP/doc/EllipseCPP_en.html)
- **Ellipse from center and a point**: Like an ellipse drawn into a bounding box with center and a corner.   / Left click, right click.
- **Ellipse from extent**: An ellipse into a bounding box  / Left click, right click.
- **Ellipse from foci**: Draws an ellipse by 2 points for foci and a point on the ellipse.   / Left click, left click, right click.https://en.wikipedia.org/wiki/Ellipse#/media/File:Ellipse-var.svg

## Rectangle:
- **Rectangle from center and a point**: Draws an orthogonal rectangle from the center and a corner / Left click, right click.
- **Rectangle from extent**: Same but with diagonal points / Left click, right click.[QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Shape/ShapeRectanglePP/doc/ShapeRectanglePP_en.html)
- **Rectangle from 3 points (distance)**: Draws an oriented rectangle by 3 points. First and second point determine the first length. Third and second point, the second length. The rectangle is oriented by the points. First and second are corners of the rectangle. Third and fourth points are projected from first and second with the distance computed.  / Left click, left click, right click.
illustration
- **Rectangle from 3 points (projected)**: https://github.com/qgis/QGIS/pull/8480 Same as precedent, but the distance is computed from a projection of the third point on the segment of the first and second point.   / Left click, left click, right click.
Illustration

## Regular polygon

Left click, and a dialog appear to enter the number of side. Right click to finish.

- **Regular polygon from center (and a corner)**: The corner defines the orientation of the regular polygon. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Shape/ShapePolygonCP/doc/ShapePolygonCP_en.html)
- **Regular polygon from 2 corners**: Creates polygons with two corners given. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Shape/ShapePolygonPP/doc/ShapePolygonPP_en.html)

Note: You may find on other software, something like "Square from center", "circle from center and radius", etc. but the are useless as it can be drawn with other tools ("regular polygon from center", "circle from center and a point", ...) and the advanced digitizing panel

## Related PR in QGIS:
First PR for the tool, with a little doc and screencast: https://github.com/qgis/QGIS/pull/4947
Second PR for rectangle by 3 points (projected): https://github.com/qgis/QGIS/pull/8480

### PR DESCRIPTION
**Pull request by SrNetoChan**
Goal:

Document the rest of the tools available on Shape digitizing toolbar

Ticket(s): Fix #4038
Fix #2179
Fix #3172

- [x] Backport to LTR documentation is required

### CODE REVIEW

**Comment by SrNetoChan** [comment]
Hi @havatv. thanks for you review, but this PR is still in draft mode. Please wait until I finish it. I plan to  run a grammar checker in the end, which may reduce the number of suggestions you need to do :-)

**Comment by havatv** [comment]
@SrNetoChan, any progress on this one?
I suggest that we merge it at this stage. Much better to have this than nothing.
You can then continue later.

**Comment by SrNetoChan** [comment]
Unfortunately, with this pandemic situation, I have three very small kids home 24x7. I can barely work... I am ok about merging this has it is for now.

I will make it ready for review.

**Comment by havatv** [comment]
Thanks, @SrNetoChan. There seems to be some merge conflicts. I don't know if you need to allow us to fix it (the "Resolve conflicts" button is disabled for me).

**Comment by SrNetoChan** [comment]
@havatv It's disabled to me to. It says I need to use the command line to fix the conflicts. Let me see if can do this quickly enough.

**Comment by havatv** [comment]
@SrNetoChan. I think this has to do with the change of structure (source/docs -> docs).
I can create a new PR with your changes, if you will allow me. :-)

**Comment by havatv** [comment]
Now it seems to be OK. You must have fixed it.  Let's merge.

**Comment by SrNetoChan** [comment]
git was smart enough to understand how to move the files I had edited.

**Comment by havatv** [comment]
Thanks, @SrNetoChan.
The QGIS Project file (working_with_vector_02.qgs) was 3.10.2. Is that a problem for the 3.4 backport?

**Comment by SrNetoChan** [comment]
That file is only used to prepare screenshot. It's not that important I think. It was a mistake to include it in here. maybe we can exclude it in the backports

**Comment by havatv** [comment]
> That file is only used to prepare screenshot. It's not that important I think. It was a mistake to include it in here. maybe we can exclude it in the backports

I will remove the project file from master, 3.10 and 3.4.

**Comment by DelazJ** [comment]
> I will remove the project file from master, 3.10 and 3.4.

No, please. There is no issue keeping it.
But If you really want, remove the diff in previous versions, not the file. I did not check this one particularly, but the set of files are there to help for screenshots and test various features/configurations.

**Comment by havatv** [comment]
Since my git skill are limited, I will just put back the old version of the file for for 3.4 and 3.10, to make sure that they can be opened with the respective versions of QGIS.

**Comment by SrNetoChan** [comment]
That sounds ok.

**Comment by havatv** [comment]
Done.

**Pull request merged**
