### PR TITLE
Update expression.rst

### PR DESCRIPTION
**Pull request by stra2da**
relation_aggregate
typo and syntax

### CODE REVIEW

**Comment by stra2da** [comment]
sorry, I'm not able to change also the expression help...

**Comment by DelazJ** [comment]
Good catch. This troubles me in the past without getting what was wrong. You can change it here https://github.com/qgis/QGIS/blob/master/resources/function_help/json/relation_aggregate#L8

**Comment by DelazJ** [comment]
Btw, in the application help, _calculation_ is also used in the`aggregate` function instead of _expression_

**Comment by stra2da** [comment]
mhm, I created a new branch with corrections
https://github.com/qgis/QGIS/compare/master...stra2da:patch-expr?diff=unified
but I'm not sure it's enougth (I'm not adeveloper...) so I didn't aPR

**Comment by DelazJ** [comment]
Yes, the json files are what is displayed in the help panel and corecting them would be enough. And if ever i'm wrong (though i'm pretty sure i'm not :smile:), you'll find smart people to kindly guide you to the missing bits.

**Comment by DelazJ** [comment]
I should have updated my dialog before sending my message. 
Your changes look good to me. You can PR imho.

**Comment by DelazJ** [comment]
Thanks

**Pull request merged**
