### PR TITLE
Update whats_new.rst

### PR DESCRIPTION
**Pull request by DelazJ**

### CODE REVIEW

**Comment by DelazJ** [comment]
Add link to changelogs page
Also remove mention of the last released doc: the advantage is that translators will not have to translate this page from release to release: done once. only the referenced hyperlink must be updated by documenters.

**Comment by yjacolin** [comment]
@DelazJ is it possible to add in one location the "replace" parameter to avoid to change many files when releasing?

**Comment by DelazJ** [comment]
@yjacolin i think it can be added in the conf.py file (where there's already |QGIS| and |CURRENT| tags.) But do you have in mind any other place that may need such replacement?

**Comment by yjacolin** [comment]
no, just go forward and we see later if we need to make more replacement.

**Comment by DelazJ** [comment]
closed inadvertently and i can't reopen. so manually merged as https://github.com/qgis/QGIS-Documentation/commit/fcecd50c621d3fa5201aae8e86d1a98e7dddd2b5

**Pull request closed without merging**
