### PR TITLE
Create an issue template file

### PR DESCRIPTION
**Pull request by DelazJ**
Trying to avoid unrelated issue reports.

@rduivenvoorde is this "compatible" with the automatic creation of issue reports from QGIS repo?

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
@DelazJ not sure what you mean: current issue reports (you mean for new features isn't it?) are created with this webhook script: 
https://github.com/qgis/QGIS-Sysadmin/blob/master/webhooks/github_feature_tracker.cgi

Is your question to incorporate the md/text of this PR into those issues?

Off course we could pull this in the python too, but note that a dev who commit's a feature actually never sees the issue that is automatically created (unless he actually goes to that issue ....)

Or do I misunderstand?

**Comment by DelazJ** [comment]
> Is your question to incorporate the md/text of this PR into those issues?

No. It wouldn't change anything I guess.
Actually, my question is whether setting an issue template for the repo could be a problem for the way the webhook is working now. Could there be a risk of malfunction (in case the template file is something mandatory in the issue creation process)? I just don't want to break working tool (that creates several useful reports), just because of some reports I want to filter out.

**Comment by Gustry** [comment]
I think the Github template is used only in the Github UI so I don't think it will be an issue for the hook

**Comment by rduivenvoorde** [comment]
I don't think it is an issue either, but in any case: just do it :-)

**Comment by DelazJ** [comment]
Ok. Thanks to you!

**Pull request merged**
