### PR TITLE
Add sphinx_copybutton extension

### PR DESCRIPTION
**Pull request by ghtmtt**
Goal:

Add the [sphinx_copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/index.html) extension in order to facilitate the code copy of the cookbook.

image

- [x] Backport to LTR documentation is requested

### CODE REVIEW

**Comment by DelazJ** [comment]
@ghtmtt how does it play in case of code-blocks with numbering? I tried few months ago and hit some issues (I can't recall what exactly) that made me step back/postpone

**Comment by ghtmtt** [comment]
Do you mean code blocks with line numbers?

**Comment by DelazJ** [comment]
yes

**Comment by ghtmtt** [comment]
@DelazJ no idea. Do you see any blocker on this? Or do you have any existing example with line numbering and the copy button?

**Comment by DelazJ** [comment]
I took some time to test the CI output and afaict spotted no issues. Good to merge IMHO. Thanks

**Comment by ghtmtt** [comment]
Thanks!

**Pull request merged**
