### PR TITLE
Revert docs on "DEFAULT_DATUM_TRANSFORMATION in Server"

### PR DESCRIPTION
**Pull request by tudorbarascu**
This reverts commit 43e87356c64d6515f22afcd405b0151f626083cc
as the code is for QGIS >= 2.16

### CODE REVIEW

**Comment by DelazJ** [comment]
@andreasneumann @elpaso has this feature been backported to 2.14 or should we revert the commit to 2.14 docs as proposed here?

**Comment by elpaso** [comment]
@DelazJ the feature was *not* yet backported (and I don't know if it will)

**Comment by DelazJ** [comment]
so better revert to avoid readers looking for it in 2.14. Thanks

**Comment by andreasneumann** [comment]
Can't we just declare that you need versions >= 2.16?
Would be a shame to keep the information from the users.
Often, also versions between server and client differ.

**Comment by DelazJ** [comment]
Shame, really? Why? Did I miss something?
This feature has been ported in testing doc (#1490) which is currently considered as on-going doc of 2.16 or 2.18. If someone is looking for documentation about a feature in QGIS Desktop/Server >2.14, I think (s)he should/must check in testing doc, not in 2.14. Information is not kept from user.
> Can't we just declare that you need versions >= 2.16?

Why would we do that for this feature and not another one? I'm not sure it's coherent with the way doc is currently written and managed : a branch per ~ release vs a single branch with versioned information. Are we moving to the latter fomula?

**Comment by andreasneumann** [comment]
Right convinced. Please include it in the testing doc.
I just used the "fix me" link on the documentation website, since I don't know how the documentation stuff works.

**Pull request merged**
