### PR TITLE
fix #issue_number 2081

### PR DESCRIPTION
**Pull request by tomtl**
This algorithm is no longer required - it's been replaced by the 'Promote to multipart' and 'Collect geometries" algorithms.

### CODE REVIEW

**Comment by ghtmtt** [comment]
@tomtl thanks a lot for the PR. Actually this other PR #2257  has the same changes (https://github.com/ghtmtt/QGIS-Documentation/blob/d45622608891ca291eaf7994405fe195982ece80/source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst#promote-to-multipart)

We are waiting for a review.

**Comment by DelazJ** [comment]
I'd propose to close this pull-request. Thanks @tomtl 
@ghtmtt could you please go through the issue list and mark all the issues your pull-requests are fixing, to avoid such situation? Thanks.

**Comment by ghtmtt** [comment]
@DelazJ I updated all the current PR with the linked issues.

**Comment by DelazJ** [comment]
Yes Thanks but please see my comment in https://github.com/qgis/QGIS-Documentation/pull/2239#issuecomment-352757648

**Pull request closed without merging**
