### PR TITLE
Added WITH_MAPTIP documentation and example to WMS GetFeatureInfo

### PR DESCRIPTION
**Pull request by elpaso**

### CODE REVIEW

**Comment by DelazJ** [comment]
Does it refer to #2205?

**Comment by elpaso** [comment]
@DelazJ I didn't notice that issue, but yes: I just wanted to add this bit to the the docs, because undocumented vendor parameters are not going to be found by users if they do not read the C++ code.

**Comment by DelazJ** [comment]
No problem, Ale. Just wanted it noticed so that we all know what is done and what's left to do. Thanks.

**Comment by SrNetoChan** [comment]
LGTM @DelazJ  any considerations?

**Comment by DelazJ** [comment]
Then, let's merge it.

**Pull request merged**
