### PR TITLE
Adds python plugin folder to env file

### PR DESCRIPTION
**Pull request by SrNetoChan**
### Description

This adds the python/plugins path to the environment file.

Goal:

This is needed when trying to run doctest on snippets that require importing processing algorithms, like #3403.

Ticket: #

- [x] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [ ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ ] This PR passes the checks.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@arnaud-morvan can you take a look? I am not sure if I don't need to add it to the build folder below as well.

Thanks!

**Comment by arnaud-morvan** [comment]
@SrNetoChan: Yes, if you use QGIS core plugins (processing) in test blocks, you should add:

```
PYTHONPATH := $(QGIS_PREFIX_PATH)/python/plugins:$(PYTHONPATH)
```

For those tests to pass with a QGIS coming from build ouput folder.

**Comment by havatv** [comment]
@SrNetoChan, do you think you can make this ready for merging based on the input from @arnaud-morvan?

**Comment by SrNetoChan** [comment]
@havatv I totally forgot this PR. I think I have added what @arnaud-morvan suggested.

**Comment by havatv** [comment]
Thanks, @SrNetoChan!

**Pull request merged**
