### PR TITLE
Processing vector geometry

### PR DESCRIPTION
**Pull request by ghtmtt**
Huge chapter of Processing: 56 algorithm descriptions. I think more eyes and hands to review are more than welcome ;)

@DelazJ please tell me if you can review this chapter and how can I be useful. Thanks

### CODE REVIEW

**Comment by DelazJ** [comment]
I could not review before the end of the week (or later) and as already requested, more reviewers are needed for the Processing Help, and it's not only because of this pull request.
Does this supersede #1972? Are the comments done there already integrated?
And yes, I think it could help to have this split into smaller pull requests

**Comment by ghtmtt** [comment]
yes it supersedes #1972 (that can be closed without merging).  Sorry for the huge PR and lots of pictures and text. 

Should I split it into smaller PR(s)? 

Thanks again @DelazJ!

**Comment by ghtmtt** [comment]
#2081 can be closed after this PR is merged.

**Comment by DelazJ** [comment]
closing as it has been split. Thanks Matteo.

**Pull request closed without merging**
