### PR TITLE
No, Marco does not manage PR queue

### LINKED ISSUE #8000: Depevolepers guide: "Who manages the PR queue" (?)
## Description

In the "Development Process" chapter of the Depevolepers guide it is stated that:

> If you feel the PR is not receiving the attention it deserves your options to accelerate it should be (in order of priority):
> ...
> Send a message to Marco Hugentobler (who manages the PR queue).

If it is still valid, then we need to add the e-mail address of Marco Hugentobler, otherwise we need to update or remove the line.

Page URL: https://docs.qgis.org/testing/en/docs/developers_guide/git.html#submitting-pull-requests

### PR DESCRIPTION
**Pull request by DelazJ**
Fixes #8000 

Goal:

Ticket(s): #

- [ ] Backport to LTR documentation is requested

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
I've sent a message to the qgis-developer ml https://lists.osgeo.org/pipermail/qgis-developer/2023-January/065474.html.

**Comment by m-kuhn** [comment]
I think @mhugent should be included in the discussion and state his position

**Comment by DelazJ** [comment]
Trying a gentle ping....

**Comment by mhugent** [comment]
Yes, please remove this line from the manual

**Pull request merged**
