### PR TITLE
add geometry less type when we create memory layer

### PR DESCRIPTION
**Pull request by Gustry**
Goal: add geometry less type when we create memory layer

Ticket(s): #

- [x] Backport to LTR documentation is required

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks @havatv

Indeed, it's an old ticket.

Can it be backported with the label. Thanks

**Comment by havatv** [comment]
@Gustry, I have added the backport label, but the backporting system seems to be down, so I don't think it would have had any effect anyway.  I can try to backport manually.

**Comment by Gustry** [comment]
Yes, I saw the email on QGIS-Dev.

Up to you if you some other backport to do soon. Or I can do it later.

**Comment by havatv** [comment]
@Gustry, backport to 3.4 fixed with #4452.

**Pull request merged**
