### PR TITLE
Add description of the size assistant

### PR DESCRIPTION
**Pull request by DelazJ**
In this PR, I:
- add description of the size assistant (#598)
- add null value handling and update screenshot (#822)
@SrNetoChan i move the size assistant description from the graduated chapter but instead of putting it under single symbol, I created a new section for it. It can indeed be used with either single symbol or categorized or graduated renderer so I put it under "proportional symbol and multivariate analysis" (it also helps to emphasize about these kinds of renderind that the size assistant helps to build). is it ok?
- add few :index: tags to help build the doc index

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@DelazJ Sounds a good idea. Please merge it. I Will update the screenshot to ubuntu as soon as this is merged.

**Comment by DelazJ** [comment]
Done. Thanks

**Comment by SrNetoChan** [comment]
@DelazJ what data did you use to create the Size Assistant screenshot? Thanks!

**Comment by DelazJ** [comment]
A fake one. Didn't find (and to be honest look for) the qgis_project that suits. I just fill a dialog with the values in the previous screenshot (with a little change due to null option added)

**Pull request merged**
