### PR TITLE
Updated PyQGIS cookbook introduction for QGIS 3.x

### PR DESCRIPTION
**Pull request by anitagraser**
Todo: Create a new page contain details of the removed "Python Applications" section which is imho too much for an introduction page

### CODE REVIEW

**Comment by pjshelton** [comment]
Hi, 
Is the reason that your update fails because there is no label for the 
Technical notes on PyQt and SIP
 section?

**Comment by DelazJ** [comment]
Hi @pjshelton
No the failure has to do with the :ref:`standalone` reference at line 128; `standalone` not being a valid "label" in the repository.

**Comment by pjshelton** [comment]
Okay. Thanks.

**Comment by DelazJ** [comment]
@anitagraser what's the plan here? Still on your todo list?

**Comment by anitagraser** [comment]
Yes but probably not realistic within the next couple of weeks, so it's ok if someone else wants to take over.

**Comment by DelazJ** [comment]
@havatv you've been working on this chapter recently and might be the one who knows better. Do you think you have extracted/reworked enough from this PR so that we can _safely_ close it? This looks _unrebasable_ to me, without headache ;)

**Comment by havatv** [comment]
@DelazJ, I have this on my to-do list.

**Comment by pjshelton** [comment]
Hi,

Sorry for not being able to be more proactive about resending the plots using a better code base.  I have had life and work take up all my time.

Phillip Shelton
SENIOR TRANSPORT MODELLER
CARDNO

[cid:image001.jpg@01D46980.F1E89930]

Phone +61 7 3369 9822  Fax +61 7 3369 9722  Direct +61 7 3877 6991
Address Level 11, 515 St Paul's Terrace, Fortitude Valley,  Queensland 4006 Australia
Postal Locked Bag 4006, Fortitude Valley 4006
Email phillip.shelton@cardno.com.au  Web www.cardno.com
CONNECT WITH CARDNO

[cid:image002.png@01D46980.F1E89930]<http://www.linkedin.com/company/cardno>

[cid:image003.png@01D46980.F1E89930]<http://twitter.com/cardno>

[cid:image004.png@01D46980.F1E89930]<http://www.facebook.com/CardnoGlobal>

[cid:image005.png@01D46980.F1E89930]<http://www.youtube.com/channel/UChnRtfJ_XrGJkMOgsrDmqBw>

Cardno’s management systems are certified to ISO9001 (quality) and AS4801/OHSAS18001 (occupational health and safety)

This email and its attachments may contain confidential and/or privileged information for the sole use of the intended recipient(s). All electronically supplied data must be checked against an applicable hardcopy version which shall be the only document which Cardno warrants accuracy. If you are not the intended recipient, any use, distribution or copying of the information contained in this email and its attachments is strictly prohibited. If you have received this email in error, please email the sender by replying to this message and immediately delete and destroy any copies of this email and any attachments. The views or opinions expressed are the author’s own and may not reflect the views or opinions of Cardno.

**Comment by havatv** [comment]
I hope that the updates done in #3087 and earlier updates have covered most of the proposed changes in this pull request.  Many thanks to @anitagraser for initiating this update.  The current version is probably not perfect, so please help improve it further.

**Pull request closed without merging**
