### PR TITLE
Fixed grammar in compatibility file in python cookbook

### PR DESCRIPTION
**Pull request by Jakob-Lanstorp**

### CODE REVIEW

**Comment by yjacolin** [comment]
Thanks!

**Comment by Jakob-Lanstorp** [comment]
Hi, 

I've  found very  nice driving glasses that  perfectly protect from brigth sunlight, and they are also so stylish, just take a look  <http://ndivikyvu.holdenmachine.com/e4lcuai>

My Best, jakob

**Comment by Jakob-Lanstorp** [comment]
Greetings, 

I've  just read amazing news, you;ve got to see  it with your  own eyes! Just take a look <http://vultongichy.gmcspecialist.com/e4urhjxl>


My Best, jakob

**Comment by Jakob-Lanstorp** [comment]
Dear, 

I  couldn't decide  which model of  phone to buy so I decided to ask you, please take a look <http://fast.courtneyfoster.com/e4hvm>


Warmly, jakob
~SUBJECT=need your advice
Dear, 

I've  found something interesting and need your opinion  about  that stuff, please  take a look  <http://fast.courtneyfoster.com/e4hvm>


Warmly, jakob

**Comment by Jakob-Lanstorp** [comment]
Yo! 


I've recently had absolutely new experience, you've got to see that! Just take  a look here <http://ltupislyndo.mulvblog.com/e4fvsbdq>

Speak to you later, jakob

**Comment by Jakob-Lanstorp** [comment]
Yo! 

I've seen  recently some  really cool things on  the web,  just take a  look <http://play.prospectingsuccesssysystem.com/e4bdsi>

Sent from my iPhone, jakob

**Comment by Jakob-Lanstorp** [comment]
Hi, 

Our mutual friends just told such  a great  news,  they have a  surprise for you! Just take a look <http://look.aclspalsonline.com/e4nghmh>

jakob

**Comment by yjacolin** [comment]
Lock conversation to avoid spam with email nothification. I don't know how it occurs but I get only spam from @Jakob-Lanstorp and on this issue.

**Pull request merged**
