### PR TITLE
Follows add missing env var

### PR DESCRIPTION
**Pull request by troopa81**
Follows #5936 to fix PR comments and insert 2 new variable in the new table

### CODE REVIEW

**Comment by troopa81** [comment]
CI is failing but I don't think it comes from my modifications. Is it? 

> make: *** [Makefile:138: doctest] Segmentation fault (core dumped)
docker.mk:4: recipe for target 'doctest' failed
make: *** [doctest] Error 2
The command "make -f docker.mk doctest" exited with 2.

**Comment by DelazJ** [comment]
Not your fault. This is part of the numerous cookbook failures that explain the red cross next to all the PRs for weeks; I made a call for help yesterday http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Travis-failing-in-QGIS-Documentation-tp5444390p5444823.html. No reaction, yet.

**Comment by troopa81** [comment]
> I made a call for help yesterday

I saw this one. I believed it was fixed. Thanks for the explanation

**Review by havatv — APPROVED** [review]
Looks fine. I have a couple of line length related suggestions.

**Comment by troopa81** [comment]
Thanks @havatv for dealing with last review comments

**Pull request merged**
