### PR TITLE
mention the fixed table item cell text format

### LINKED ISSUE #5866: [feature][layouts] Allow setting per cell text format in manual text tables
Original commit: https://github.com/qgis/QGIS/commit/18a36e46227b238d831d3b64f8b4f7f9151c6748 by nyalldawson

Individual cells (or selections of multiple cells) can have an preset
text format set, which overrides the default text format for those cells.

Sponsored by City of Canning

### LINKED ISSUE #5871: [feature][layouts] Allow cells in manual text tables to have expression
based contents
Original commit: https://github.com/qgis/QGIS/commit/1f9b9c8c9e7baa3631ea53cb3973f4f5e0ae944c by nyalldawson

Allows individual cells from a manual text table to take their contents
from a preset expression. Expressions have access to the full layout
item expression context, allowing cells to calculate and display
metadata style values or aggregate based calculations.

Sponsored by City of Canning

### PR DESCRIPTION
**Pull request by lajunek**
Introduction and main properties for the fixed table item section inluding the cell text format.

Goal: Users shall get precise information about setting the cell text format in the table designer of the fixed table item properties.

Ticket(s): fix #5866 fix #5871

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by lajunek** [comment]
@DelazJ @havatv I added the fixed table section to the attribute table chapter and so extended this. It is called the Table items now. Apart from small fixes that still have to be done, are you ok with this solution?

**Comment by DelazJ** [comment]
@lajunek Yes, it should be fine to have both in the same page. Makes sense the way you organize it. Thanks.

**Comment by DelazJ** [comment]
@lajunek please fix red crosses before merging changes

**Comment by lajunek** [comment]
@DelazJ can we fix the errors with a new pull request?

**Comment by DelazJ** [comment]
Already done in #6326

**Pull request merged**
