### PR TITLE
Added screenshots for Examples section in graphical model - issue #7370

### LINKED ISSUE #7370: Allow setting Examples in graphical model help  (Request in QGIS)
### Request for documentation
From pull request QGIS/qgis#47561
Author: @nyalldawson
QGIS version: 3.26

**Allow setting Examples in graphical model help **

### PR Description:
A new 'Examples' section has been added to the graphical model help editor dialog, allowing users to enter their own custom examples to help explain usage of the model.

We also now show more instructive help for models in the qgis_process tool, including outputing any example help which has been set.

Refs NRCan Contract#3000739399

### Commits tagged with [need-docs] or [FEATURE]
"[feature][processing] Allow setting Examples in graphical model help\n\nA new 'Examples' section has been added to the graphical model help\neditor dialog, allowing users to enter their own custom examples\nto help explain usage of the model."

### PR DESCRIPTION
**Pull request by selmaVH1**
fixes #7370 I have changed the key screenshots in this section to maintain consistency within the same operating system and added description for the Example section in graphical model.

### CODE REVIEW

**Review by timlinux — COMMENTED** [review]
Thanks @selmaVH1 Just one house keeping item - for the images you replaced with new images having new names, did you remove the old images if they are not being used anywhere? 
image

**Comment by selmaVH1** [comment]
@timlinux no, I didn't, they are still in the folder. Just in case that new ones don't get approved. Should I remove old images?

**Comment by selmaVH1** [comment]
@DelazJ sure, thanks for the suggestion.

**Comment by DelazJ** [comment]
> Just in case that new ones don't get approved. Should I remove old images?

Without the old images in the diff, it is hard to know what you are replacing, and whether better.

**Pull request merged**
