### PR TITLE
Adding help to processing selection functions

### PR DESCRIPTION
**Pull request by DelazJ**
@alexbruy what would be the output when the algorithm processes a selection? Thanks

### CODE REVIEW

**Comment by alexbruy** [comment]
Are you talking about algorithms like "Select by attribute", "Select by location" etc? These algorithms don't produce any output, instead they select features which match given criterion in the source layer.

**Comment by DelazJ** [comment]
yes i'm talking about those algs . Hence, what would fill [the output section](http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vector_selection_tools.html#id33) (any special expression to use)? Or should it be erased ?

**Comment by alexbruy** [comment]
Output in this case is the same vector layer as input, but with selection.

**Comment by DelazJ** [comment]
yes, but looking at the UI of these algs, there's no `output` parameter. I guess this should also be removed from their doc. Am i right?

**Comment by DelazJ** [comment]
Finally, I add some information on outputs, given that the `output` section is not placed under `Parameters`, hence can not be considered as a parameter. I understand it as "what do i get if i execute this algorithm?"

**Pull request merged**
