### PR TITLE
add romanian translation team

### PR DESCRIPTION
**Pull request by tudorbarascu**

### CODE REVIEW

**Comment by yjacolin** [comment]
LGTM

**Comment by DelazJ** [comment]
This list is really out of date, at least since the move to Transifex. Maybe should we find a way to automatically update it, see #669.

**Comment by tudorbarascu** [comment]
@DelazJ For now, there are 3 options:
* Merge it
* I can close the pull request + maybe a rebase with deletion of all contributors
* Find a way for automatically update it (does anyone have time?)

**Comment by DelazJ** [comment]
Merge it! it makes it less outdated than before :)

**Pull request merged**
