### PR TITLE
Hide the fix me button

### LINKED ISSUE #3559: Move the "fix me" buttons in the 2.18 release pages to 3.4
## Description

With 3.4 being the release we maintain now, it's time to remove the "fix me" links that open the source pages and translation files, in 2.18 documentation. And enable them for 3.4 branch.

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

### PR DESCRIPTION
**Pull request by DelazJ**
Another attempt to remove fix me button on 2.18 pages (no more fixes on this branch - fix #3559)

Ticket: #

- [ ] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [ ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ ] This PR passes the checks.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
Does not seem related to the PR.  It's failing when trying to download the transifex package or something.

**Comment by SrNetoChan** [comment]
It seems that the transifex-client needs to be updated. 0.9 is not compatible with Python 3:

https://github.com/transifex/transifex-client/issues/38

So maybe jump to 0.12.5 (what is used in master now)?

**Comment by DelazJ** [comment]
I wonder if it's worth the effort (though I don't know how big is the effort). A lot of things have changed since 2.18 (we upgrade sphinx and all the dependencies, add doctest and I think it's normal it fails). Is that not possible to (temporarily?) disconnect travis (from 2.18?) and merge my commit. Otherwise I could simply close both this PR and the (thus "unfixable") issue report (will try to live with that 😄 )

**Comment by SrNetoChan** [comment]
If we disconnect travis, it wont build the docs, or will it? Can I try to patch your PR directly? I was trying to do a PR on your branch but it fails...

**Comment by DelazJ** [comment]
> Can I try to patch your PR directly?

Of course. Feel free to do whatever you think is right.
> I was trying to do a PR on your branch but it fails...

That's weird but that's not the first time. My PR allows maintainers edit so normally you should be able to change it.

**Comment by SrNetoChan** [comment]
Here you go! Done! :-D

**Comment by DelazJ** [comment]
Great!

**Comment by DelazJ** [comment]
Let's close another 2.x-period issue. Thanks @SrNetoChan .

**Pull request merged**
