### PR TITLE
Create virtual environment on the fly

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Need details about how this is deployed to avoid breaking something.

### CODE REVIEW

**Comment by ghtmtt** [comment]
this is a great enhancement, thanks! So basically (on Linux) machines, documentation can be build eith a venv even if the users has not a venv installed, right?

**Comment by arnaud-morvan** [comment]
@ghtmtt: Yes, Python virtual environment is created and used on the fly with option `-f venv.mk`.
And with this option if you change something in REQUIREMENTS.txt, it is also reinstalled on the fly ;-).

**Comment by arnaud-morvan** [comment]
@ghtmtt @rduivenvoorde: I just rebased on master to resolve conflicts. For me this is ready for merge, but I do not have push right, so if this looks good and works for you, feel free to merge.

**Comment by rduivenvoorde** [comment]
Hi Arnaud, I did not have time yet to really dive in it, but what you showed on the hackfest looks very good.
I'll just try and check when I'm home.

For others: Arnaud changed the work flow to incorporate the QGIS docker desktop in it, making it possible to (IF you want to use Docker to build) also test the python scripts from the PyQGIS cookbook using the QGIS from the docker.

He also made it simpler to create/use a virtual env (venv) in the work dir.

@arnaud-morvan what I'm wondering if if we now have to pull a new image from Docker hub just because (I think) you used the nightly docker build? 
And if it is still possible to have the html-docker and pdf-docker on hub (because these are now depending on the more often changing qgis-docker? But maybe I understand wrong, so give me some time to look into this plz. 
OR should we just pull and see what happens :-)

**Comment by arnaud-morvan** [comment]
@rduivenvoorde : AS see things, it could be possible in QGIS-Documentation/.travis to create a qgis/documentation docker image, on top of qgis/qgis docker image (in the same version), adding sphinx and pdf related dependencies, and push it on docker hub.
After that, standard user will only need to pull this images to build html, pdf and run doctests using docker.

**Comment by ghtmtt** [comment]
@rduivenvoorde @DelazJ @havatv @SrNetoChan I think this PR is harmless (besides than useful). Meaning that if users want to build the doc in the old ways they can.

What we should do, when all the PR of @arnaud-morvan are merged, is to add some *reviewers guidelines* with all these steps explained (especially for #3503).

Can I go on?

**Comment by havatv** [comment]
OK with me, but I don't have the full picture here.

**Comment by SrNetoChan** [comment]
I tried running `make html` and `make fasthtml` and it seems to work perfectly. But I am unsure about any implication on pdf creation or translations. I would like @rduivenvoorde to test it first.

Besides, @arnaud-morvan with the merge of #3503 this one has now conflicts.

**Comment by arnaud-morvan** [comment]
Already merged with #3503

**Pull request closed without merging**
