### PR TITLE
Title label decoration

### PR DESCRIPTION
**Pull request by diethard2**
This includes 3 commits that should not be squashed because they have atomic changes
the first commit adds icons and changes to substition.txt and substitution.rst
the second commit makes changes to the general_tools.rst of user manual updating the title_label_decoration and updating the icons for the Grid and Title Label decoration.
Th third commit is made by havatv who added another icon in the substitution guidelines manual.

2nd try, first time it was approved by havatv, but due to many changes included on master and a change on origin I did a push after a rebase, now wise because this leads to history of commits that was not very nice. I created a new brand and cherry picked the 3 commits in right order.

Ticket(s): fix#5018

- [x] Backport to LTR documentation is required

### CODE REVIEW

**Comment by diethard2** [comment]
@havatv the backport to 3.10 did fail. Have you any idea why? Is it because @rduivenvoorde is busy with filling transifex. Anyway it is merged in master including your change. If you want to have another try to backport this change to 3.10 please go ahead. I am a bit uncertain about the backport procedure.

**Comment by havatv** [comment]
@diethard2, I think I managed to backport it to 3.10. I have never tried this (more manual) procedure before - nice to have tried it.

**Comment by DelazJ** [comment]
The backport not is broken and does not work if you use the "merge" action. Using "rebase" seems to work. So either you merge in master with rebasing or you cherry-pick the commits to 3.10.
Also be aware that splitting the section as done here, other than the points I raised in the issue report, breaks the link from the help button in these dialogs

**Comment by havatv** [comment]
> Also be aware that splitting the section as done here, other than the points I raised in the issue report, breaks the link from the help button in these dialogs

Thanks for pointing this out. I hope this is fixed by #5040.

**Comment by DelazJ** [comment]
@havatv actually, no! Sorry if I was unclear. I was not referring to the GUI chapter in docs but to the actual help button in the application (ie , Open the title/copyright decoration dialog and press "help" button). That button is connected to the HTML url of the section, aka, to the title of the section: the section title changes, the url needs _unfortunately_ to be fixed in QGIS code repository.

**Comment by havatv** [comment]
Thanks for pointing this out, @DelazJ. I have made a PR against the QGIS repository that I hope will fix it.

**Pull request merged**
