### PR TITLE
Update menus according to OS

### PR DESCRIPTION
**Pull request by DelazJ**
This PR updates the list of tools available under the menus entries.
Due to differences related to the platform being used, are listed in the table the tools that are available in most of the OSes and a comment is then added to inform where this tool can be found in other platforms (most of the time osx or kde).

### CODE REVIEW

**Comment by yjacolin** [comment]
LGTM

**Comment by DelazJ** [comment]
Why does Travis take soooo long: two hours yet???

**Comment by yjacolin** [comment]
Travis for open source community shares the ressource between all open source projects. Usually it is faster the morning but if there are some waiting tasks, we have to wait or may be travis has some issues.

**Comment by yjacolin** [comment]
See https://www.traviscistatus.com there was a problem yesterday and a high level of job at 9h00.

**Comment by DelazJ** [comment]
Thanks for the explanation, Yves

**Comment by yjacolin** [comment]
Travis test started 12 mn ago :)

**Pull request merged**
