### PR TITLE
Add an example of expression to list features in a layout map item

### PR DESCRIPTION
**Pull request by DelazJ**
I don't know if it should be in this general page, in the layout label item page (and/or in the json example in code) but here it's.

### CODE REVIEW

**Comment by roya0045** [comment]
I'm not sure the with_variable is needed but it showcase the function. I usually use than when something is needed more than once. But I'd say this is fine there.

**Comment by roya0045** [comment]
Good then! Personally I dislike the generic aggregate and used the dedicated ones, but that's a minor gripe.

**Comment by DelazJ** [comment]
In this context (layout), I'm not sure it's possible to use the concatenate function since there's no layer.

**Comment by roya0045** [comment]
In the layout the atlas feature should be the available layer. I agree that if you need to operate on another one the generic expression may be good.

**Pull request merged**
