### PR TITLE
HTML Build action uses fasthtml

### PR DESCRIPTION
**Pull request by SrNetoChan**
Goal:

Change the command used by the HTML Build action
This allows faster check, with no internacionalization
It also does not build in nitpick mode, allowing the build to
complete even if there are some warnings. This allows documenters
to see all errors at once, and not just the first one.

Ticket(s): #

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by SrNetoChan** [comment]
Here's one example.

To the following pull request I have added some problems. The build action still performs to the end, creating the artifact file, but if we check the action details, we can inspect all warnings, for example:

https://github.com/SrNetoChan/QGIS-Documentation/pull/5/checks#step:5:1134

https://github.com/SrNetoChan/QGIS-Documentation/pull/5/checks#step:5:1431

I think this way the action can fully replace the need to build the docs locally, as the contributor can inspect the HTML output, and he can check the log for all errors.

**Comment by SrNetoChan** [comment]
I wanted to use something more fancy that this... Check this one:

https://github.com/ammaraskar/sphinx-action

Unfortunately, our Sphinx version is simply too old for it...

**Comment by havatv** [comment]
Looks like a nice feature to me, but I am not familiar enough with Sphinx to provide sensible feedback.

**Comment by SrNetoChan** [comment]
Because we have Travis, the build will still fail if there are problems with the sphinx syntax or there are any files missing.

But on travis the build runs on nit-pick mode, which exits in failure at the first warning. If there are more errors, the documenter will fix one by one, almost one commit at a time to find the next issue.

With this action, not only we can download and preview the HTML, we can see the full log and see all warnings.

**Comment by DelazJ** [comment]
@SrNetoChan :+1:  all issues in one is more helpful than one by one.
> Unfortunately, our Sphinx version is simply too old for it...

Should not be an issue too long. I'm updating @rduivenvoorde work and should PR something in upcoming days for completion.

**Comment by SrNetoChan** [comment]
In that case I will merge this. Thanks!

**Pull request merged**
