### PR TITLE
Make the build less permissive and catch errors

### PR DESCRIPTION
**Pull request by DelazJ**
Eg, neither #5141 nor #5047 should have passed 
This PR is expected to fail because I want to test the setting and let an error (fixed in #5150)
Part of this needs manual backport to other releases.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Hi @DelazJ looks good to me. Will pull and test further. 
I'm also thinking about enabling nitpicking builds on translations.
As we will (probably) not pull every build anymore, we could 'tx pull' one language, create a PR which will then be build/checked then pull PR for every Language...
But that is future work.
Thanks for making THIS work!

**Comment by rduivenvoorde** [comment]
Current build has some warnings now, for duplicate label names *between files*... Never seen that one before?
Will do PR for that

**Comment by rduivenvoorde** [comment]
Should this be pulled in 3.10 too?

**Comment by rduivenvoorde** [comment]
Mmm, that is funny, my first build after this commit showed:

```

/home/richard/git/QGIS-Documentation2/docs/user_manual/managing_data_source/opening_data.rst:459: WARNING: duplicate label figure_mesh_datasource_manager, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_mesh/mesh_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:5: WARNING: duplicate label showlabels, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:57: WARNING: duplicate label labels_text, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:90: WARNING: duplicate label labels_formatting, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:151: WARNING: duplicate label labels_buffer, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:185: WARNING: duplicate label labels_background, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:239: WARNING: duplicate label labels_shadow, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:345: WARNING: duplicate label labels_placement, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:355: WARNING: duplicate label cartographic, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:417: WARNING: duplicate label figure_labels_placement_line, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:473: WARNING: duplicate label figure_labels_placement_polygon, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
/home/richard/git/QGIS-Documentation2/docs/user_manual/style_library/label_settings.rst:485: WARNING: duplicate label labels_rendering, other instance in /home/richard/git/QGIS-Documentation2/docs/user_manual/working_with_vector/vector_properties.rst
```

But after fixing only one, the next builds did not show warnings anymore??
Also this PR itself did not trigger Travis...
Weird

**Comment by DelazJ** [comment]
> Should this nitpickey stuff also be pulled in 3.10?

Yes, the PR should be backported to 3.10 (and 3.4), excepted the changes in the processing file. I planned to do it but I'm currently on macOS and have a broken state of the repo with GitHub app. Could try tonight.
> I'm also thinking about enabling nitpicking builds on translations.

That would stop the translations build if an error is met or the build will continue? 
What scares me is that this could be very noisy: we'll get a lot of warnings (eg French translations have more than 80 warnings - I think 3.4 had 3 times more the last time I build) and we should ensure that making awareness of errors is of any interest.
I think QGIS.ORG is responsible of a good English docs and each language community is responsible of their versions. We just provide the infrastructure to all (equity!) but they are responsible of their doc's quality. And if there are issues with building their docs, the communities are more concerned than the docs team. Something that could be nice to help them is to output those warnings in a txt file and have a script that makes it "readable" for anyone, with maybe only filename and buggy line/string. Then, up to any language member to fix their errors.
Anyway, as you said, that's a future work. Let's focus on stability of the base, first.

**Pull request merged**
