### PR TITLE
show how to add/modify group wms data

### PR DESCRIPTION
**Pull request by tudorbarascu**

### CODE REVIEW

**Comment by tudorbarascu** [comment]
I think there's a trick here cause when I build successfully it deletes the  ``source/static/user_manual/working_with_ogc/set_group_wms_data.png`` that I added with ``git add -f ..``

What's the work-flow to add a screenshot?

**Comment by DelazJ** [comment]
Screenshots are added in Resources folder. See http://docs.qgis.org/testing/en/docs/documentation_guidelines/writing.html#add-new-screenshots

**Comment by tudorbarascu** [comment]
@DelazJ Thanks. I just noticed the documentation guidelines. I'm kind of rusty for now.

**Comment by tudorbarascu** [comment]
Any idea why the CI didn't trigger when I pushed the rebase?

**Comment by yjacolin** [comment]
@tudorbarascu that's weird, travis-ci should start even after a rebase.

**Comment by yjacolin** [comment]
May I suggest a new push?

**Comment by tudorbarascu** [comment]
Done

**Pull request merged**
