### PR TITLE
Fix geometry functions and add new variables

### PR DESCRIPTION
**Pull request by DelazJ**

### CODE REVIEW

**Comment by yjacolin** [comment]
fix  #818? Could you add issue number in your PR and milestone :)

**Comment by yjacolin** [comment]
LGTM

**Comment by DelazJ** [comment]
No it doesn't fix #818. Those functions are not yet documented in QGIS Expression dialog and even though I understand through their name what they are supposed to do, the result I get is not that evident.
I opened an issue report (http://hub.qgis.org/issues/14259) asking for their description

**Comment by DelazJ** [comment]
no Travis check?

**Pull request merged**
