### PR TITLE
Fixed typos + API update for memory layer section

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by DelazJ** [comment]
Actually it's not a typo; it's an outdated documentation (hence, the other occurrences). Changes to 3 in this chapter don't go beyond line 248 as mentioned in the warning.

**Comment by anitagraser** [comment]
@DelazJ xMiniminum was a typo and so was layer instead of vl

**Comment by anitagraser** [comment]
Good to know that there is a warning. The file is so big that I hadn't seen it and I doubt any reader would see it there in the middle of the page. Putting it at the top of the document might make it more likely that people notice it.

**Comment by anitagraser** [comment]
@ghtmtt I'll try to find the time to update the sections between line 248 and the memory layer section. Not sure I have time for more in the next days.

**Comment by ghtmtt** [comment]
@anitagraser if you have time it would be great so in a single PR we have many different fixes. If not, nevermind, we can fix them once the PR is merged.

**Comment by havatv** [comment]
I suggest that we merge this.  Then it will not be lost in case someone else starts on this part.

**Comment by ghtmtt** [comment]
OK to merge also for me.

**Pull request merged**
