### PR TITLE
Add supported model formats

### LINKED ISSUE #2139: [FEATURE] support 3d models
Original commit: https://github.com/qgis/QGIS/commit/7d3cf228d89e18b02f4095e1bb8c884e73fa0ea9 by wonder-sk

Unfortunately this naughty coder did not write a description... :-(

### PR DESCRIPTION
**Pull request by anitagraser**
fixes #2139

Goal:

Ticket(s): #

- [ ] Backport to LTR documentation is requested

### CODE REVIEW

**Comment by DelazJ** [comment]
@anitagraser Do you plan to add the third point also or is the PR enough as is? _no strong opinion, myself_
>  potentially Klas Karlsson's tutorial https://www.youtube.com/watch?v=rV0m_YN84Q0

**Comment by anitagraser** [comment]
I wanted to ask if there are other cases where the docs are pointing to video tutorials yet? I'm currently leaning towards not adding the video.

**Comment by DelazJ** [comment]
* There is https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html?highlight=tim%20sutton#annotation-tools
* There is this [request](https://github.com/qgis/QGIS-Documentation/issues/7485#issuecomment-1146593196) from yourself
* I came across this https://github.com/sphinx-contrib/youtube extension that embeds online videos but I still need to figure out how to [properly  render in PDF](https://github.com/DelazJ/QGIS-Documentation/tree/contribVideo) (we can still limit them to HTML build or simply use [raw:: html](https://github.com/DelazJ/QGIS-Documentation/tree/embedVideo), still PDF outputs?)

So, yes, I've been looking recently in ways to add those online materials in the docs and wanted to do more tests before I raised whether it is a path we want to take or not. Maybe time has come?
And we need to find relevant materials (eg, the one from Tim above is quite outdated).

**Comment by anitagraser** [comment]
Let's merge without the video. It's not ideal, almost 1 hour and most of it is in Blender rather than QGIS.

**Pull request merged**
