### PR TITLE
Add missing GDAL grid algorithms

### LINKED ISSUE #2159: [processing][FEATURE] add IDW with neareast neighbor search
Original commit: https://github.com/qgis/QGIS/commit/46662443a8a2b7adce9517f7f2b0f129387091d0 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

### LINKED ISSUE #2160: [processing][FEATURE] add linear interpolation
Original commit: https://github.com/qgis/QGIS/commit/4272b8b7adef4c7b9bb6752971fed65847998faf by alexbruy

Unfortunately this naughty coder did not write a description... :-(

### PR DESCRIPTION
**Pull request by DelazJ**
fixing help path and reorganize parameters order to match algorithms dialog
Fixes #2159 fixes #2160

### CODE REVIEW

**Comment by ghtmtt** [comment]
the moving average algorithm in my QGIS has a slightly different order of parameters and name. Not sure how we can handle this to make consistent

**Comment by DelazJ** [comment]
What's the name used and the order you have? Mine (master 3.1 Windows) is like the one in the help.

**Comment by DelazJ** [comment]
Isn't that the same order as in the description?
About parameter name, I did not touch it and opted to keep the short version used in gdal doc itself (and the parameter description should help to figure out the correspondence)

**Comment by DelazJ** [comment]
@ghtmtt do you still see an issue with this PR?

**Comment by DelazJ** [comment]
@ghtmtt?

**Pull request merged**
