### PR TITLE
Merge pull request #1 from qgis/master

### PR DESCRIPTION
**Pull request by lajunek**
Merge my master fork with qgis:master

### Description

Goal:

Ticket: #

- [ ] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [ ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ ] This PR passes the checks.

### CODE REVIEW

**Comment by DelazJ** [comment]
@lajunek I'm afraid I don't understand the purpose of this PR and merge...

**Comment by lajunek** [comment]
@DelazJ answer to your question: I wanted to update the master of my fork lajunek as it was far behind master

**Comment by Gustry** [comment]
> @DelazJ answer to your question: I wanted to update the master of my fork lajunek as it was far behind master

@lajunek It's not what you did. You merged your master *into* the main master branch. And your master branch was already up to date, so nothing has changed with this PR, you just created a merge commit in the main repo, which is not ideal. Anyway, it didn't break anything.

Not need to create a PR if you want to update your master (of your fork)

**Comment by lajunek** [comment]
@DelazJ thanks for your advise. I'm trying to get used to the online system

**Comment by lajunek** [comment]
@Gustry thanks for your advise. I'm trying to get used to the online system

**Pull request merged**
