### PR TITLE
Add descriptions and algorithm details for the QGIS vector overlay tools.

### PR DESCRIPTION
**Pull request by sokolic**

### CODE REVIEW

**Comment by timlinux** [comment]
Cool @sokolic - hopefully you had a chance to chat to @volaya first & saw my email about their intention to possibly change the processing documentation system...?

**Comment by sokolic** [comment]
Thanks @timlinux. Yes, have written to Victor and am awaiting his response.

**Comment by yjacolin** [comment]
Should we close this PR? There are some conflicts now!

**Comment by sokolic** [comment]
Yes, you can close it. I've got a copy of the changes I made and can issue a new PR if necessary.

**Pull request closed without merging**
