### PR TITLE
Fix history line

### PR DESCRIPTION
**Pull request by SrNetoChan**
### Description

This commit fixes a bad squashing where individual contributions would be lost in the history. this makes the history a bit more poluted, but more fair for those who have worked on the PycookBook during the hackfest

- [x] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [ ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ ] This PR passes the checks.

### CODE REVIEW

**Comment by DelazJ** [comment]
> SrNetoChan requested your review (DelazJ ) on this pull request. 

😮 0 file changed?  I'm not sure of the two last commits but I think you add and revert..
Imho, you need to:
- revert the merge on **master** branch first
- checkout (a copy of ) the pycookbook branch
- rebase onto master: you'll possibly have some conflicts to fix (will the rebase set the commits to you too? I don't remember but am not sure it does) and maybe squash your own commits
- open the PR

**Comment by SrNetoChan** [comment]
This just rewrites the history, so there will never be chages to the files.

**Comment by SrNetoChan** [comment]
That was what I did. I reverted and then merged the old branch.

**Comment by DelazJ** [comment]
I'm not sure I fully understand the logic (and how assignment are fixed) but Travis is green, you know what you are doing and I trust you both, so merge when you want.

**Comment by SrNetoChan** [comment]
@DelazJ Shit, you were right... now the history is even worst and the problem was not solved. I will have to go and the use hard reset and start over. sorry about that, it seems I actually was not understanding what I was doing.

**Pull request merged**
