### PR TITLE
Fix grammar in coordinate_reference_systems intro

### PR DESCRIPTION
**Pull request by scottstanie**
Goal: Just a quick update for some of the wording in the start of the CRS tutorial for clarity.

Ticket(s): #

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by havatv** [comment]
Thanks, @scottstanie!

**Comment by havatv** [comment]
@DelazJ, should we backport this?

**Comment by DelazJ** [comment]
No imho.

**Comment by havatv** [comment]
OK. No backporting of this one.

**Pull request merged**
