### PR TITLE
Adds doctest_global_cleanup to clear QgsProject instance

### PR DESCRIPTION
**Pull request by SrNetoChan**
### Description

Goal:

Clear the QGIS project instance in every rst file to avoid problems in docs testing

Ticket: #

- [ x ] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [ ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ ] This PR passes the checks.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
Let's see if this still solves the problem of having a tests failing because of reusing existing objects (QgsProject.Instance())

**Comment by SrNetoChan** [comment]
@ghtmtt @DelazJ @havatv This looks like a better solution. what do you think?

**Comment by havatv** [comment]
Looks good to me. Nice to have isolation as the default.

**Comment by DelazJ** [comment]
thanks @SrNetoChan

**Pull request merged**
