### PR TITLE
[WIP] Work with relations

### PR DESCRIPTION
**Pull request by ponceta**
Work with relations (altered work with vector tree)

Goal:
Enhance the relations documentation by putting it forward.

Ticket(s): # Fix https://github.com/qgis/QGIS-Documentation/issues/7558

- [ ] Backport to LTR documentation is requested

### CODE REVIEW

**Comment by ponceta** [comment]
Not ready yet, no use to get it into the workflows.

**Comment by DelazJ** [comment]
@ponceta, Thanks for providing a pull-request. Really appreciated. I have few questions, if I may:
- If I'm not wrong, relations are only vector-based feature. Would it not be better to have it under the "working with vector" hat, as you were suggesting? as a 15.4 entry
- what do you think about @3nids suggestion for instead a page for both "joins" and "relation" features? i.e. a single place for the techniques to connect layers to each others
- (**_depends on decisions from above points_**) I'm not sure we need two files for relation (an index page + the description). There won't be much to say in the index page. A single page, straight way to access the information, should be enough imho (see e.g. mesh or tile vector chapters)

**Comment by ponceta** [comment]
@DelazJ Thank you for your good insights

- Work with relations : I had to try it on both (16. or 15.4) to see how it looks from the user's perspective, because you could have several sections on relations (relations/interface/types/edition (and maybe more to come)) (it seems fine to me in 15.4, I'll make a proposition in that way)

- About joins : A simple join 1:1 relations chapter is actually missing and should IMHO reference this section (it is usefull to have the Joins properties where it is actually). About that, an advice section could be good to hint the user on whether use a simple join or a project relation

- Two pages : same doubt here when I did it, if we go on 15.4 then we should not have this index page anymore.

A question mark for me, it is `working with relations` or `working with joins and relations` ? (the simpler the better I would say)

**Comment by DelazJ** [comment]
I'm fine with your todo list
> A question mark for me, it is working with relations or working with joins and relations ? (the simpler the better I would say)

I think there's a bit too many "working with..." How about "Connecting layers", "Connecting data across layers", "Dynamic link between layers"... ie not necessarily mention the features but the need they answer?

**Comment by DelazJ** [comment]
@ponceta what is the status here? From a quick glance, there's a lot of visible `todo`...

**Comment by DelazJ** [comment]
@ponceta any plans?

**Comment by DelazJ** [comment]
superseded by #8435

**Pull request closed without merging**
