### PR TITLE
Merge pull request #1 from qgis/master

### PR DESCRIPTION
**Pull request by nickbearman**
Updates

### CODE REVIEW

**Comment by DelazJ** [comment]
@nickbearman, do you need help for something?

**Comment by nickbearman** [comment]
I was trying to update my fork of the documentation (at nickbearman/qgis-documentation) but ended up pressing the wrong button! I think it was OK in the end.

**Comment by nickbearman** [comment]
Thanks @DelazJ 
What's the best way of updating my fork of the documentation (at nickbearman/qgis-documentation)? I've been trying to work it out, but haven't made much progress!

**Comment by DelazJ** [comment]
@nickbearman if you are using github web interface, you can do a PR in your own repo from `qgis:master` (head fork) to your branch (the base fork) and merge the commits into your branch. Your branch will then have all the contents of the official one though it'll be one commit forward (which actually contains nothing). But this is not really a problem (!). You can then make new changes to the branch and pull request as usual against `qgis:master`

But if you want to have your branch even with `qgis:master`, AFAICT you've reached GitHub web interface limitations that (could?) have been exposed in the [step-by-step guidelines](http://docs.qgis.org/2.14/en/docs/documentation_guidelines/first_contribution.html#using-git-command-line-tools): cleanly update existing branch with commits only from upstream. 
If you want to update existing branch without this trick of PR, I think the best step is to manage it in a local repo with a git (GUI) client and use its functions of merge or push (command lines or not).

Note: using the `fix me` link at the bottm of the page helps you work on new and up to date branch (even with `qgis:master`). So it could be a solution to have updated branches and delete as things go on, useless branches.

**Comment by nickbearman** [comment]
@DelazJ Thanks, I think I've got my head around it now. My latest OR was through Git on the terminal (I'm on OSX) using a local repo. Thanks for the step-by-step guidelines - they were very useful, and worked well. I did get a permission denied entry, which turned out to be an SSH issue.

**Comment by DelazJ** [comment]
Nice to see that the "step-by-step guidelines" has a fan :-). I had missed it when I began contributing and spent a lot of time to learn git, sphinx, rst... Not all people willing to contribute can spend enough energy so it was obvious that having a consolidated guidelines may ease contribution for all. Now we need to advertise it.
If you have ideas of subjects that can improve these guidelines, things a beginner may need or if you find errors to fix, feel free to inform us. Any contribution is very welcome.

The issue you encountered might be caused by the use of git@github.com:qgis/QGIS-Documentation instead of git://github.com/qgis/QGIS-Documentation. I personally use the second style without key problem as far as I remember. I then really not know if it's the 'qgis/QGIS-Documentation' that should be locally cloned or '<Your-Username>/QGIS-Documentation'. Reminds me [an old PR](https://github.com/qgis/QGIS-Website/pull/327)

**Pull request closed without merging**
