### PR TITLE
Place the images in PDF where they are expected in the rst

### PR DESCRIPTION
**Pull request by DelazJ**
avoiding accumulation of screenshots at the end of exercises, making them almost useless (iow download the training manual in pdf and try to understand any logic in the screenshot - I really wonder if there are people using the PDF...)

### CODE REVIEW

**Comment by SrNetoChan** [comment]
Won't this affect all the Pdf's?

**Comment by DelazJ** [comment]
Yes. Should it not? Any issues you are worrying about?
PS: pull request generate now a pdf version, for check

**Comment by SrNetoChan** [comment]
My concern is pages with large empty spaces because a image is too big and is moved to the next page.

**Comment by SrNetoChan** [comment]
Check page 13 of the users manual

**Comment by DelazJ** [comment]
> Check page 13 of the users manual

Good example. Check corresponding page (**and following**) in the [current output](https://docs.qgis.org/testing/pdf/en/QGIS-testing-DesktopUserGuide-en.pdf) and let me know your preference.
On a general count:
* User manual: from 1287 pages to 1303 (+16)
* Training manual: from 667 pages to 706 (+39)

I think that the delta is reasonable (beside chapters always begin on an odd page) given the gain of sense/comprehension. And while browsing half of the TM, I did not came across many huge empty space.

Another point: we should be more "directive" on the screenshot resolution and resizing...

**Comment by DelazJ** [comment]
Any decision here?
With the Answers chapter split and spread over the exercises, you now get more (if ever possible) confusion. e.g. in the training manual:
- p13 (/26): the first screenshot in the Answer frame should be displayed earlier; it now displays at the right place the screenshot of the solution (the one below) is expected to be.
- p15 (/28): you get a map in the Answer frame, while none is expected.

**Comment by SrNetoChan** [comment]
Go ahead with it. Since I don't expect people to print the PDF, the
difference in number of pages is acceptable.

+1

A segunda, 8/03/2021, 16:14, Harrissou Sant-anna <notifications@github.com>
escreveu:

**Comment by DelazJ** [comment]
Great. Thanks @SrNetoChan

**Pull request merged**
