### PR TITLE
fix Line Density algorithm ID

### PR DESCRIPTION
**Pull request by root676**
This is just a quick fix of the algorithm ID for the Line Density algorithm. The algorithm is native - not a python implementation. 

Goal: fix the broken algorithm ID of Line Density

- [x] Backport to LTR documentation is requested

### CODE REVIEW

**Comment by DelazJ** [comment]
@root676 when you say "broken ID" do you mean that it doesn't work using qgis instead of native?

**Comment by root676** [comment]
@DelazJ that is exactly what I meant. :)

**Comment by DelazJ** [comment]
That's weird. native is supposed to be a subgroup of qgis, unless things have changed recently. `qgis` should replace `native` without issues, not the reverse. See https://github.com/qgis/QGIS/issues/44671

**Comment by root676** [comment]
Oh - then that's my mistake. I didn't know that `qgis` also works with `native` algorithms. In this case - of course - nothing was broken. Thanks for pointing me to the issue.

**Pull request merged**
