### PR TITLE
Add appendix listing QGIS network connections

### PR DESCRIPTION
**Pull request by anitagraser**
Addresses https://github.com/qgis/PSC/issues/55

### CODE REVIEW

**Comment by anitagraser** [comment]
TODO Anita: do another update from google doc in https://github.com/qgis/PSC/issues/55

**Comment by DelazJ** [comment]
Since there's no merged cells in the table, I suggest we moved away from the complex and hard to update grid table formatting to the list table.
That said, I'm not convinced the docs is the right place for this document but... if the site isn't in the right shape to display it, let's put it there in the meantime. _another reason to update our website_

**Comment by DelazJ** [comment]
Unrelated and already fixed in master build failures. So this could be technically merged anytime.
@anitagraser Do we mention somewhere (website?) that these information are available here ? Otherwise i'm afraid it's known only by us.

**Comment by anitagraser** [comment]
@DelazJ Thanks. Yes, according to https://github.com/qgis/PSC/issues/55 the plan is to add a link to https://qgis.org/en/site/forusers/index.html. I'll get to it.

**Comment by DelazJ** [comment]
@m-kuhn 
> Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 88a365e27c632f8941f1201331061cd38c8a7d7c,0d7adfd81b5ef71a8426799650116a4998d16676,13a8d1a1048d25889fbe9249ccce49aa89aa4e97,6408baa5cda45472a8ee75874a3e4c5e7c1f41d8

Isn't this a wrong command (with comma)?

**Pull request merged**
