### PR TITLE
Rapidlasso patch 1 (help pages)

### PR DESCRIPTION
**Pull request by rapidlasso**
First try to add help pages to LAStools

### CODE REVIEW

**Comment by yjacolin** [comment]
@rapidlasso is it ready to be merged?

**Comment by rapidlasso** [comment]
Hello,

finally someone notices this. I am not sure it is ready to be merged as I
authored it directly on github.com because I was not able to fork all of
QGIS at the code sprint / hack fest after FOSS4gE. But I think that my
"documentation" bits do not break anything as I followed an existing
example. Could someone with a working QGIS fork merge this and check if the
few LAStools processing tools whose documentation was added are still
working correctly (and unmerge in the unlickely event of breakage)?

Regards,

Martin

**Comment by yjacolin** [comment]
@rapidlasso I will test it right away. I will closed it or let you know about any problem or success.

**Comment by yjacolin** [comment]
@rapidlasso I "merged" your files from your branch https://github.com/rapidlasso/QGIS-Documentation/tree/rapidlasso-patch-1.

I added index.rst file feel free to send me a short description to add inside.

Sorry for my mistake which lead to revert the initial merge from your PR.

**Comment by rapidlasso** [comment]
Will this be propagated to QGIS 2.10 and 2.11 ... ?

**Comment by yjacolin** [comment]
yes (2.10 and) 2.12 :) Note that 2.10 and 2.12 will be the same doc release.

See http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/index.html if you want to check.

**Pull request merged**
