### PR TITLE
Statistic summary can be copied to clipboard

### LINKED ISSUE #2550: [FEATURE] Copy statistics panel content to clipboard button
Original commit: https://github.com/qgis/QGIS/commit/f63d5ad9acb3d6a8317a20743f937f773bbcf1b1 by nirvn

Unfortunately this naughty coder did not write a description... :-(

### PR DESCRIPTION
**Pull request by DelazJ**
fix #2550

### CODE REVIEW

**Comment by gioman** [comment]
This PR is accurate.

**Comment by DelazJ** [comment]
It howevermisses an uptodate screenshot (i can not run a Ubuntu machine)

**Comment by gioman** [comment]
> It howevermisses an uptodate screenshot (i can not run a Ubuntu machine)

I can do that.

**Comment by DelazJ** [comment]
Would be nice @gioman. Thanks.

**Comment by gioman** [comment]
> Would be nice @gioman. Thanks.

statistical_summary

**Comment by DelazJ** [comment]
Thanks @gioman
Could you please directly make a pull-request to either my branch or master directly? It will ease integration.
Also, maybe we can resize the screenshot to fit its content and avoid the blank space in the middle (and maybe also reduce in height and show less statistics?)

**Comment by gioman** [comment]
> Could you please directly make a pull-request to either my branch or master directly? It will ease integration.
> Also, maybe we can resize the screenshot to fit its content and avoid the blank space in the middle (and maybe also reduce in height and show less statistics?)

sure, will do asap.

**Comment by DelazJ** [comment]
@gioman I'll merge as is and we will add the screenshot later.

**Pull request merged**
