### PR TITLE
Fix some text inconsistencies with 2.18 version

### PR DESCRIPTION
**Pull request by JonathanWillitts**
In version 2.18 the option is 'Fixed distance buffer' not 'Buffer(s)'

### CODE REVIEW

**Comment by JonathanWillitts** [comment]
I've updated this, though does the fact that the screenshots are now inconsistent with the body text cause a problem?

I've spotted other such menuselection/guilabel inconsistencies following the tutorial.  Do you want PRs for those too?

**Comment by DelazJ** [comment]
@JonathanWillitts 
> In version 2.8 the option

You meant 2.18, right?
> I've updated this, though does the fact that the screenshots are now inconsistent with the body text cause a problem?

I'd favor aligning screenshots with text. So if you can also do it, go ahead. Otherwise, you can open an issue report to make other contributors aware of the need to update these screenshots. Note that this dialog has got another changes from 2.18 to 3.0 (not harmful for your PR though)

>I've spotted other such menuselection/guilabel inconsistencies following the tutorial. Do you want PRs for those too?

Please, do 😄 . It's good to have people help and remove inconsistencies from the doc so feel free to propose any improvements you feel good.
Thanks @JonathanWillitts

**Comment by JonathanWillitts** [comment]
Yes I meant 2.18! - updated PR and comment to reflect this.  

Are Windows screenshots ok, or do you prefer to keep them Mac screenshots throughout?

**Comment by DelazJ** [comment]
They actually should be Linux screenshots (see guidelines at http://docs.qgis.org/2.18/en/docs/documentation_guidelines/writing.html#managing-screenshots) but personally I'm fine with Windows up to date screenshots than linux outdated ones, still with an issue report to remind purists to have it fixed.
what do u think, "mister Screenshot" @SrNetoChan ?

**Comment by JonathanWillitts** [comment]
Ah, the Mac reference was in relation to the: 

> Note: The screenshots for this course were taken in QGIS 2.0 running on MacOS.
on http://docs.qgis.org/2.18/en/docs/training_manual/introduction/preparation.html

**Comment by JonathanWillitts** [comment]
...though I'm happy to add some Windows screenshots to this PR if that helps.

**Pull request merged**
