### PR TITLE
Substitution icon for mActionForm #609

### PR DESCRIPTION
**Pull request by SrNetoChan**
Creates a substitution Icon for mActionForm. This should be merged with #609 fixes by @yjacolin .

### CODE REVIEW

**Comment by DelazJ** [comment]
@SrNetoChan aren't these changes already done by @yjacolin in #884 ?

**Comment by yjacolin** [comment]
@DelazJ no, I just added a default icon to not break test. But now that I read your contribution to the documentation process I know where to find the icon in QGIS src file :)

**Comment by DelazJ** [comment]
Didn't expect it to be so quickly useful :)

**Comment by yjacolin** [comment]
@DelazJ you are right, I already added the subsitution variable: https://github.com/qgis/QGIS-Documentation/pull/884/files#diff-64f700244d8204b08e2278507b6312f8R762

**Comment by DelazJ** [comment]
It could be nice to have it added to the [list of substitutions](http://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#attribute-table)

**Comment by SrNetoChan** [comment]
@DelazJ I will add it to the list of substitutions. @yjacolin Do you want me to replace the default icon? After that, Is it ok to merge this?

**Pull request merged**
