### PR TITLE
Get rid of all 32 and 34 substitution

### PR DESCRIPTION
**Pull request by ghtmtt**
Not needed anymore after branching 3.4 ref #3507 

After the travis is happy the PR will be cherry-picked also for master (leaving 3.6 substitution)

### CODE REVIEW

**Comment by DelazJ** [comment]
@ghtmtt i'm not sure of 7c51c16

**Comment by ghtmtt** [comment]
too used to push to master :) thanks @DelazJ closing this and making a new one

**Comment by DelazJ** [comment]
😃 Yeah, we need to change our habits and be more careful. Just for reference, clicking the Edit button next to the PR title allows to modify the target branch (no need to open another PR)

**Comment by ghtmtt** [comment]
oh wow, didn't know that, thanks!

**Pull request closed without merging**
