### PR TITLE
Consolidating github actions with best practices

### PR DESCRIPTION
**Pull request by DelazJ**
[Apply security best practices to actions (inspired by https://github.com/qgis/QGIS/pull/49188 and done using https://app.stepsecurity.io/)
- Restrict permissions for GITHUB_TOKEN
- Add security agent for Github hosted runner
- Pin actions to a full length commit SHA
- I had to guess and apply some changes in backport and autolabel workflows as the actions we relied on are unknown by the service

Also raise Python version in actions to 3.9 and various cleanup.
Not 100% understanding (nor did I test) all the changes here so we'd need to monitor the repo behavior after this is merged. And of course, feedback/review welcome.

### CODE REVIEW

**Comment by Gustry** [comment]
> Pin actions to a full length commit SHA

A tag is a nickname to a commit SHA. So IMHO, when you use a tagged version in the background it's easier to have it's tag. It's easier to read and mainly to update later (no need to copy/paste), and I don't think that tools such as "dependabot" or "renovate" will update commit SHA.

**Comment by DelazJ** [comment]
No strong opinion. I'm just following [GH advices](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions). I'm doing changes on the actions to fit the needs we have, including allowing them to push to the repo. So considering that I'm not a dev, I try to hold my back as much as possible. About dependabot, it seems to take care of that (https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/). No idea what "renovate" was (and it is not used here).

**Comment by DelazJ** [comment]
Any objections to merge this?

**Comment by Gustry** [comment]
Ok for me.
I didn't know dependabot would manage git hash easily as well, thanks

**Pull request merged**
