### PR TITLE
Correct windows paths

### PR DESCRIPTION
**Pull request by DelazJ**
See: https://github.com/qgis/QGIS-Documentation/issues/6179#issuecomment-735259992
Thanks @JBacc1. Opening the PR for a better visibility and feedback.

### CODE REVIEW

**Comment by DelazJ** [comment]
@agiudiceandrea @Gustry Can any of you have a look please? I think you have more experience than me in this area. Thanks

**Comment by agiudiceandrea** [comment]
Hi @DelazJ, <qgispath> is actually used ambiguously in the text and the proposed change (`c:\\<qgispath>\\apps\\<qgisrelease>\\python`) correctly removes the ambiguity.

I'm not sure instead if the second proposed path to add to PYTHONPATH is really needed in the pyqgis developer cookbook intro: in that chapter the user learns to correctly set the system environmental variables in order to solve some issues when importing the qgis.core module.
The second proposed path (`c:\\<qgispath>\\apps\\Python37\\lib\\site-packages`) is useful in importing other modules like QtCore (as stated by @JBosm), but AFAIK it shouldn't be strictly necessary in order to import qgis.core.

**Comment by Gustry** [comment]
Sorry, I don't have windows right now to have a look.

**Comment by jef-n** [comment]
`%OSGEO4W_ROOT%\bin\python-{qgis,qgis-ltr,qgis-dev,qgis-ltr-dev,qgis-rel-dev}.bat` starts python with the passed script with the environment setup to the respective qgis package.

**Comment by JBacc1** [comment]
Hello @agiudiceandrea,
I tried again to `import qgis.core` without the second PYTHONPATH addition (`c:/<qgispath>/apps/Python37/lib/site-packages`). Python won't import qgis.core with the error message : `ModuleNotFoundError: No module named 'PyQt5.QtCore'`.
It seems qgis.core imports QtCore, and that the second addition is also necessary.

Full message error:

  File "my_script.py", line 7, in <module>  
    from qgis.core import *  
  File "C:/Program Files/QGIS 3.10/apps/qgis-ltr/python\qgis\__init__.py", line 70, in <module>  
    from qgis.PyQt import QtCore  
  File "C:/Program Files/QGIS 3.10/apps/qgis-ltr/python\qgis\PyQt\QtCore.py", line 24, in <module>  
    from PyQt5.QtCore import *  
ModuleNotFoundError: No module named 'PyQt5.QtCore'

**Comment by agiudiceandrea** [comment]
Hi @JBacc1, are you sure you are using Python shipped with QGIS?
I can follow the exact steps of the guide without issue to import qgis.core if PYTHONPATH is only set to `c:\\<qgispath>\\apps\\<qgisrelease>\\python`:

```
C:\>WHERE python
C:\Program Files\QGIS 3.10\apps\Python37\python.exe

C:\>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import qgis.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'qgis'
>>> quit()

C:\>SET PYTHONPATH=C:\PROGRA~1\QGIS3~1.10\apps\qgis\python

C:\>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import qgis.core
>>> print(qgis.core.Qgis.QGIS_VERSION)
3.10.11-A Coruña
>>> quit()

C:\>
```

**Comment by DelazJ** [comment]
Hi,
Can someone summarize what we need to do in the docs? Or provide the best fix, please? Thanks

**Comment by JBacc1** [comment]
Hello,
@agiudiceandrea has a point. I was trying to access the qgis.core from outside the python delivered with QGIS. 
But: my usecase was using qgis.core inside a far larger project that I would not have considered developing within QGIS. 
If the qgis.core is to be used only for small developments directly within or close to QGIS, then limiting the modification to the first change seems ok to me. 
If qgis.core may be considered for larger-scale projects with blocks outside the QGIS scope, the second change should be considered, if not in the main text, at least as a note somewhere in the doc.

**Comment by DelazJ** [comment]
This PR went stale and is a bit confusing to me now.
I suggest someone who understands provides a summary of what the fix is or (even better) opens a PR or we let it close.

**Pull request closed without merging**
