### PR TITLE
Stacked diagrams documentation

### LINKED ISSUE #9277: [feature] Introduce stacked diagrams (Request in QGIS)
### Request for documentation
From pull request qgis/QGIS#58568
Author: @gacarrillor
QGIS version: 3.40

**[feature] Introduce stacked diagrams**

### PR Description:
This PR extends the QGIS diagram module allowing it to create and display **stacked diagrams**, i.e., diagrams located side by side. We've also taken the opportunity to move the diagram settings from a modal dialog to the **Styling dock widget**.

Stacked diagrams can be configured and **displayed horizontally or vertically**. The **spacing** between the so called subdiagrams can also be configured.

Stacked diagrams allow users to create complex diagrams like **population pyramids**.

Stacked diagrams can show **mixed subdiagram types** (e.g., a pie chart alongside a histogram) and users can add as many subdiagrams as they want. Moreover, subdiagrams can use **different renderer types**: e.g., one subdiagram could use a single category renderer, whereas the other could use a linearly interpolated one.

Subdiagrams can **set their own size and their own legend settings** (e.g., one subdiagram could show its categories in the legend, whereas another one could hide its own categories).

Subdiagram **ordering** is given by item ordering in the Stacked Diagram page's list. In the future, users could re-arrange subdiagram ordering by dragging and dropping subdiagrams (left as follow-up).

Note there are some shared settings like placement **settings** (e.g., over point), **that the stacked diagram will take from its first subdiagram**. Thus, other subdiagrams won't be able to set or change those specific settings, unless they become the first subdiagram in the stacked diagram. Therefore, when editing a subdiagram that is not located in the first place, we show labels to let users know why they don't see the expected widgets (e.g., placement ones) and where they can find them (i.e., in the first subdiagram).

**GUI Stacked Diagrams**

https://github.com/user-attachments/assets/7b5a55af-45cd-4231-85b9-c6031b783a3f

**GUI Single Diagram**

Before / After ([click](https://downloads.tuxfamily.org/tuxgis/tmp/borrar/single_diagrams_before_after.png) to see it in large size)
image

image

**Other samples** 
(Note the corresponding point feature's geometry)

expected_stackedhistograms

expected_stackedpieshorizontalwithspacing

image

image

Mixed renderer type (pies using single category and histograms using linearly interpolated one):
expected_stackedpiehistogram

Nested stacked diagrams (just because we can! Not exposed through GUI, but possible in core and showcased via unit test):
expected_stackeddiagramsnested

-------------
Includes tests.

Additional fixes:
 + Fix #58501
 + Fix #58782 

----------

Funded by [Landesamt für Vermessung und Geoinformation (LVG) Vorarlberg](https://vorarlberg.at/-/landesamt-fuer-vermessung-und-geoinformation-l-1) in collaboration with the [QGIS user group Switzerland](https://qgis.ch/).

### Commits tagged with [need-docs] or [FEATURE]

### PR DESCRIPTION
**Pull request by gacarrillor**
Fix #9277 

 + [x] Brief description, icon and substitution.
 + [x] Detailed subsection.
 + [x] Screenshot.

### CODE REVIEW

**Comment by gacarrillor** [comment]
@DelazJ, I've generated quite a few candidates for the Stacked Diagrams figure.

Please let me know if you prefer another one among these to replace the already submitted one:

1)
Screenshot from 2024-11-01 19-06-05

2)
Screenshot from 2024-11-01 19-12-03

3)
Screenshot from 2024-11-01 19-12-28

4)
Screenshot from 2024-11-01 19-26-45

5)
Screenshot from 2024-11-01 19-26-57

6)
Screenshot from 2024-11-01 19-28-17

7)
Screenshot from 2024-11-01 19-28-27

**Comment by gacarrillor** [comment]
Please backport it to v3.40.

**Comment by DelazJ** [comment]
@gacarrillor sorry for the silence. Will try to get back to you next week at most (I didn't have time to test the feature yet, I'm curious hw you define the project to render your legend).
PS: image 2 and 3 above are identical, aren't they? and @selmaVH1 your opinion is very welcome.

**Comment by gacarrillor** [comment]
@DelazJ, no worries and thanks for the message.

If you want to test it, please use a nightly build, 3.40.0 ships a (~~_shameful_~~) bug that prevents users to set up a new diagram.

Concerning the legend:
Well, the categories themselves are configured in each subdiagram. And regarding the `Population` section below the category items. It can be configured in the second subdiagram (`Legend Entries for Diagram Size...`), so it appears at the bottom:

image

I'm not an expert on those legend figures, so I had to play a bit to match a bit the horizontal orientation of population diagrams. Far from ideal but I wanted to reach some sort of scale hint.

BTW, that's why I uploaded other screenshot options hiding the `Population` section, just in case the figure seems too strange.
Here another try, making the points a bit lighter (I think the points shouldn't really exist, but that's the most acceptable I could get):

stacked-diagram_2


in case you want to replicate it, here you can find the data and the project itself:
[stacked_diagrams.zip](https://github.com/user-attachments/files/17684707/stacked_diagrams.zip)



Finally, images 2 and 3 differ on the diagram effects (drop shadow).

**Comment by gacarrillor** [comment]
> Thanks @gacarrillor, this looks completely fine to me, it's clear where the Population legend comes from, you've added the :ref: so that's all good, users can follow the links and create the legend as described. The only thing I don't understand is how this legend is applicable or how the population lines are visible on the map (f they should be visible at all)? I opened your project and played with it, but I still don’t get it. Maybe the Population legend isn’t necessary for this example, so I would go with screenshot without it...

Thank you @selmaVH1 for your comments. You're right, ideally, the legend should show bars instead of lines. I just wanted to do some experiments on what could be achieved at the moment, but I agree we could go instead with the screenshot without the population legend, that is, picture no. 2.

I'll update the PR accordingly and let you know.

**Comment by gacarrillor** [comment]
@selmaVH1, I've replaced the screenshot to avoid showing the population legend figure. Thanks for the suggestion!

**Pull request merged**
