### PR TITLE
Clean parameters display

### PR DESCRIPTION
**Pull request by DelazJ**

### CODE REVIEW

**Comment by SrNetoChan** [comment]
LGTM

**Comment by yjacolin** [comment]
What is the need for space at the begining of the line?

**Comment by SrNetoChan** [comment]
Makes it look better. It indent the description after the parameters. I needed to build it in order to understand.

**Comment by yjacolin** [comment]
thanks!

**Comment by DelazJ** [comment]
@yjacolin The fix is about http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vector_general_tools.html#execute-sql (same line for parameter and its description)
@SrNetoChan you can also view how the changes can look like by clicking the View button from Files tab. That would lead you to https://github.com/DelazJ/QGIS-Documentation/blob/b4f16ae8a39fe1f7edb7f505231be0411243cc0c/source/docs/user_manual/processing_algs/qgis/vector_general_tools.rst#execute-sql while the current rendering is https://github.com/qgis/QGIS-Documentation/blob/bb3d2a53e3528285ad57eb5af2be60f159797f94/source/docs/user_manual/processing_algs/qgis/vector_general_tools.rst#execute-sql

**Pull request merged**
