### PR TITLE
Manual backport of 5715 (TM basic map)

### PR DESCRIPTION
**Pull request by havatv**
Goal: Manual backport of 5715 (basic map, training manual)

Ticket(s): #5715

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by havatv** [comment]
The substitution error has also been fixed in master (69cf7da).

**Comment by DelazJ** [comment]
> The substitution error has also been fixed in master (69cf7da).

Did you check whether it is an error in master: https://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#selection-and-expressions?

**Comment by havatv** [comment]
> > The substitution error has also been fixed in master ([69cf7da](https://github.com/qgis/QGIS-Documentation/commit/69cf7da41d73deb843d5b40b90c33c9d630e2838)).
> 
> Did you check whether it is an error in master: https://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#selection-and-expressions?

Did not check that, but could not find any problems now.

**Comment by DelazJ** [comment]
Having green travis checks (which was already the case in master) does not mean that the contents are correct, that there's no problems.
69cf7da41 is reverted in 26905dc. The icons are in the url I already sent and just compare with either:
* an attribute dialog in master
* the github preview of the file
* or the html build generated by the PR or your commit

**Comment by havatv** [comment]
> Having green travis checks (which was already the case in master) does not mean that the contents are correct, that there's no problems.
> [69cf7da](https://github.com/qgis/QGIS-Documentation/commit/69cf7da41d73deb843d5b40b90c33c9d630e2838) is reverted in [26905dc](https://github.com/qgis/QGIS-Documentation/commit/26905dca20b5d62b5c94a16e247a94f8deacfb1f).

Thanks.

> The icons are in the url I already sent and just compare with either:
> 
>     * an attribute dialog in master
> 
>     * the github preview of the file
> 
>     * or the html build generated by the PR or your commit

I know, sorry. This time I was working on 3.12, and did not check master.

**Pull request merged**
