### PR TITLE
Removed probable leftover from testing

### PR DESCRIPTION
**Pull request by DiGro**
line 23 :  Found : "testing changes."  I suspect this frase was a leftover from developers testing. Since it seems to make nog sense in this way, I removed it. If necessary it need to be refrased to avoid confusion.

### Description

Goal: Avoid confusion in user documentation

### CODE REVIEW

**Comment by havatv** [comment]
Thanks, @DiGro!

**Comment by havatv** [comment]
I also updated 3.4.
@DiGro, if you are sure that the change applies both to master and 3.4, there is a mechanism to indicate that in the pull request.

**Comment by DiGro** [comment]
> 
> 
> I also updated 3.4.
> @DiGro, if you are sure that the change applies both to master and 3.4, there is a mechanism to indicate that in the pull request.

My mistake. I'm working on the documentation of 3.4 but are making pull requests for master. My bad.
I'll be more careful next time

**Comment by havatv** [comment]
@DiGro, you are doing the right thing - making the pull request against master.  What is missing is to indicate that the pull request should be backported to 3.4.

**Comment by DelazJ** [comment]
@DiGro Indeed, better provide the fix on master and remember to check the `[ ] Backport to LTR documentation is required` though I'd assume, given the "youth" of 3.4 branch, this kind of issues affect both branches and backport should be automatically considered. And thanks for hunting these issues.
@havatv about backporting, I think that adding the label after the PR is merged also creates the backport PR (in case you don't want to handle it manually).

**Pull request merged**
