### PR TITLE
Get rid of all 32 and 34 substitution

### PR DESCRIPTION
**Pull request by ghtmtt**
Not needed anymore after branching 3.4

After the travis is happy the PR will be cherry-picked also for master (leaving 3.6 substitution)

### CODE REVIEW

**Comment by ghtmtt** [comment]
no idea why travis is failing. It seems referring to another PR...

**Comment by DelazJ** [comment]
I wonder if it has to do with you reopening #3510 (same branch) while travis was checking... Let's see!
Btw, maybe remove tags in expression.

**Comment by ghtmtt** [comment]
seems working :) merging?

**Comment by DelazJ** [comment]
Don't you want to (partly) cherry-pick the removal of the tags from the expression chapter beforehand?

**Comment by ghtmtt** [comment]
ok done. I looked in everywhere and seems that we don't have no more 32 and 34

**Pull request merged**
