### PR TITLE
Add "Render layers as groups" to style panel

### LINKED ISSUE #7133: Render layers as groups (Request in QGIS)
### Request for documentation
From pull request QGIS/qgis#46183
Author: @nyalldawson
QGIS version: 3.24

**Render layers as groups**

### PR Description:
This exposes the ability to render group layers, as described by qgis/QGIS-Enhancement-Proposals#235.

When a group is selected in the layer tree the styling dock will show a new panel for controlling the appearance of the group as a whole, with options for group opacity, blend mode and layer effects.

image

Sponsored by Andrew Fletcher.

### Commits tagged with [need-docs] or [FEATURE]
"[feature] When a group is selected in the layer tree, the layer\nstyling dock now shows an option to control the rendering\nappearance of the entire group\n\nBy selecting \"Render Layers as a Group\", the whole set of layers\npresent in the group will be rendered as a flattened object during\nmap renders. This means that the opacity and blend mode assigned\nto the group will apply to the flattened version of all the\nchild layers, instead of applying to each layer one-by-one.\n\nThis allows for styling results such as groups of layers which\nobscure each other, but overall are rendered as semi-opaque."

### PR DESCRIPTION
**Pull request by felixfeckler**
fixes #7133

Goal:

Ticket(s): #

- [ ] Backport to LTR documentation is requested

### CODE REVIEW

**Comment by DelazJ** [comment]
I think "Render layers as groups" is a new concept that deserves more explanation than the issue report provides. Eg It changes how related layers are rendered. You might want to get the substance of this feature in the [referenced QEP](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/235).

**Comment by felixfeckler** [comment]
Okay i see. Can add some more informations, but i am not sure where. What do you think? 
My approach would be to expand the descreption in the Layer Styling Panel. The other place i found could be https://docs.qgis.org/3.22/en/docs/user_manual/introduction/general_tools.html#interact-with-groups-and-layers . Otherwise there is not much information about group layers, or am i missing something?

**Comment by DelazJ** [comment]
The "interact with groups and layers" section seems a good candidate to me

**Comment by DelazJ** [comment]
Superseded by #7946

**Pull request closed without merging**
