### PR TITLE
Add last_value function

### PR DESCRIPTION
**Pull request by tjukanovt**
Adds last_value algorithm description to the documentation: https://github.com/qgis/QGIS-Documentation/issues/6623

Nothing special. Just one line added to the algorithm descriptions as I wanted to test the whole documentation process. This is my first commit and PR to the docs, so be kind 🙋🏼‍♂️

Ticket(s): #
https://github.com/qgis/QGIS-Documentation/issues/6623

### CODE REVIEW

**Comment by DelazJ** [comment]
Thanks @tjukanovt 
Unfortunately, this file is autogenerated (see [header](https://github.com/qgis/QGIS-Documentation/edit/master/docs/user_manual/working_with_vector/expression_help/Aggregates.rst)) based on help in the expression functions dialog. The change in #6623 does not affect any expression function _per se_ but the [aggregate algorithm](https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#qgisaggregate). So that's the place we might need to update.

**Comment by tjukanovt** [comment]
@DelazJ Ok. Got it. As the other aggregate functions are neither documented inside that processing algorithm (which makes perfect sense), maybe the right place to make the change then is the function help files in the resources/function_help/json/ folder in the qgis/QGIS repository?

**Comment by DelazJ** [comment]
@tjukanovt I'd tend to agree. last_value and first_value are functions accessible only from the aggregate algorithm; I couldn't find them elsewhere (thought they came from stats panel but no) and no idea why they were not added as common aggregate parameter/function in expression dialog. Worth a try.

**Comment by DelazJ** [comment]
@tjukanovt Closing this for now

**Pull request closed without merging**
