### PR TITLE
Sample for using tables in algorithms parameters and outputs

### PR DESCRIPTION
**Pull request by SrNetoChan**
This is a starting point to #2745 
This is how it is rendered.

image

### CODE REVIEW

**Comment by ghtmtt** [comment]
looks good. Can you try with an algorithm that has some images in the parameter? e.g. buffer

**Comment by DelazJ** [comment]
Nice. Just some quick remarks/questions:
- what about moving python identifier under its own column? It needs to be obvious and I don't feel it's the case... I guess you put it there because they are both names.
- and maybe move the data type under the parameter name? Do we need to keep the `[]` (wonder if it'll look better between \`\` or a :guilabel: )
- Are we limited to 3 columns? Or is that possible to add another one (need to find which between default value, data type, optionality... would need its own column though)

**Comment by SrNetoChan** [comment]
> Can you try with an algorithm that has some images in the parameter? e.g. buffer

We can definitely put images inside the table, but they will probably be too big for the column width. Otherwise, in these cases, maybe we need to push the images to the description.  I will give it a try later.

**Comment by SrNetoChan** [comment]
>     what about moving python identifier under its own column? It needs to be obvious and I don't feel it's the case... I guess you put it there because they are both names.

yes, I thought they were related, but I agree that the way it is now it may not be clear enough. I started by having a double title for that column Parameter Name | Python identifier, but it messed with the way the header looks.
>     and maybe move the data type under the parameter name? Do we need to keep the [] (wonder if it'll look better between `` or a :guilabel: )

We don't need to keep the brackets. I would avoid using inside guilabel or `` as those are normally reserved for other kinds of stuff (even inside a table).

I would keep that column in separate as it's a definitly different thing from the name.

>     Are we limited to 3 columns? Or is that possible to add another one (need to find which between default value, data type, optionality... would need its own column though)

We can add as many columns as we like. My take here was to keep the table compact and still have a nice to read description column. I don't think we need a separate column for each thing, we just need to , specially for things that are not always present (like optional, or default)

Actually, for optional, I was wondering if we couldn't use the universal * somehow.

Anyway, I can play around later and show you guys how it looks.

**Comment by SrNetoChan** [comment]
> I was thinking the same. Moving the data type under the parameter so we can still have 3 columns (and not 4) for the python identifier.

I am not sure about it. I really like the Type column to be separated so that the user can quickly see the type of inputs he needs. And it will get confusing when the Type information is too much (e.g., [vector: Polygon, Lines].

Anyway, I will give it a shot later.

**Comment by DelazJ** [comment]
> We can add as many columns as we like.

example in saga docs: http://www.saga-gis.org/saga_tool_doc/2.2.0/grid_analysis_18.html

**Comment by SrNetoChan** [comment]
@ghtmtt this is how it looks with figures in it

image

**Comment by SrNetoChan** [comment]
This was my try to make the identifier more clear, but the header gets pretty unbalanced

image

**Comment by SrNetoChan** [comment]
moving the identifier to a new column

image

**Comment by SrNetoChan** [comment]
moving the type to the name column:

image

**Comment by SrNetoChan** [comment]
I think I still prefer the first one :-). @ghtmtt @DelazJ now it's up to you.

**Comment by ghtmtt** [comment]
well done @SrNetoChan! I like the second one more ;) What about moving the identifier column at the end  of the table? Maybe it is more useful for *skilled* people

**Comment by SrNetoChan** [comment]
@ghtmtt Sorry, by second you mean?

**Comment by ghtmtt** [comment]
The second picture ;)

**Comment by SrNetoChan** [comment]
@ghtmtt so the one with identifier on the header as well?

**Comment by ghtmtt** [comment]
I mean this https://github.com/qgis/QGIS-Documentation/pull/2770#issuecomment-404787273

but what about moving the identifier column to the end of the table (as the last column?). I think that it is the *less* important to have here, meaning that at a first glance the users might want to know the input, type and read the description..

**Comment by SrNetoChan** [comment]
> but what about moving the identifier column to the end of the table (as the last column?). I think that it is the less important to have here, meaning that at a first glance the users might want to know the input, type and read the description..

+0  on that. I think it makes sense there after the name, but if you guys prefer at the end, so be it.

Don't you think that the description column gets too small? That is my main concern with separating the identifier to it's own column. I can try and steal some space from the other columns. currently they are 20% 20% 20% 40%

**Comment by SrNetoChan** [comment]
@DelazJ any opinion on this?

**Comment by DelazJ** [comment]
Yes, sorry. My vote would go to the [4 columns one](https://github.com/qgis/QGIS-Documentation/pull/2770#issuecomment-404787273). Information are clearer this way imho. And yes, if you can, steal some space from the other columns. Isn't that possible to let that managed automatically or are the widths a requirement for this kind of tables?
Things I don't see in the examples is where do we put eg, enumeration values and Optional mention?

**Comment by SrNetoChan** [comment]
@DelazJ 4 columns it is then. I can try to see what happens if I remove the width information.
At the first example you can see a Optional example. I would put it under the name inside parentheses. The enumeration options I would put in the description.

**Comment by SrNetoChan** [comment]
@DelazJ if I remove the columns :width: all columns get the same width, so 25% each in case of 4 columns.

**Comment by SrNetoChan** [comment]
Doing some more experiments. Changed the columns' size to 15 10 15 60.

image

Removed the brackets on the type, and added and fictional example of optional

image

Felt that the Type column got confusing without the brackets because of the defaults. Used uppercase at the type name and put the defaults inside parenthesis. Also added an enumeration example on the description, including the integers needed to be used on python for each option

image

Did not like the parenthesis, so tried using brackets instead for options and defaults

image

@DelazJ @ghtmtt let me know what you think of this.

**Comment by SrNetoChan** [comment]
@DelazJ @ghtmtt @yjacolin bump

**Comment by ghtmtt** [comment]
I like the second one. Here my thoughts:

* I'd get rid of all the brackets: (Optional), (Default: 5), [vector: any]... Given that all this words/sentences/whatever are in an ordered way I see brackets useless
* the title **Identifier**.. mmm it looks clear to us but maybe not so clear for users (even advanced). What about adding **Python Identifier**? If too long also **Py identifier**

**Comment by yjacolin** [comment]
I fully agree with @ghtmtt !

**Comment by SrNetoChan** [comment]
I see this work as secondary if compared with the number of issues we have for the 3.4 release.
I will continue this work if I have time for it. Ideally will need to create a script that convert the original format in a table, even if it needs some fixes after.

**Comment by havatv** [comment]
Definitely an improvement.  I hope it can be implemented soon.

**Comment by havatv** [comment]
@SrNetoChan, @DelazJ, @ghtmtt,
I have started to use the table format, and since there seemed to be close to consensus on using "Parameter 2" (https://user-images.githubusercontent.com/3607161/43171450-0a490fcc-8fa2-11e8-9426-ddace17b8070.png), I have used that.  Since some of this has now been merged, I hope that you agree that it looks great :-) . Examples:

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html#join-attributes-by-nearest-38

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#check-validity

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectortable.html#add-x-y-fields-to-layer-38

If we can agree that this is a reasonable solution, I am ready to incrementally update the processing algorithm documentation with the new table format (requires checking the name of the parameters in the code, so it will take a bit of time, but I have some time now).

We are very closed to completing documentation of QGIS processing algorithms for both 3.4 and 3.10, so it would be nice to also get this done - the sooner the better :-)

**Comment by DelazJ** [comment]
Hi @havatv 
Thanks for the call and this is also what I told myself when I got notification of #4409. We need to decide on this topic as soon as possible to avoid redoing things later. I'll come up later with my remarks but any reason to not have added the `` to the identifiers? That would have made the tables more colorful imho.

**Comment by havatv** [comment]
I am OK with using `` for the identifiers.

**Comment by SrNetoChan** [comment]
Hi!

Sorry for not being able to keep working on this (or any other thing regarding the documentation...)

Thanks @havatv for bringing this back. Coming back to this after so much time almost makes me see things differently, I have only three ideas that I would like to share:

1 - Add Python Identifier to the header, to make it clear. We probably should mention somewhere what a "Python Identifier" is.
2 - Already said by @DelazJ make the identifiers "red" and fixed-size font, it suggests the user that it's has something to do with code.
3 - What do you think about moving any necessary image (like the one in the buffers) to the outside of the table with a nice caption? Otherwise, they will be too small, I think.

It would be nice to have a python script that could parse the old structure into the new one, with just a few manual tweaks. That was my initial idea, but again, time flies...

**Comment by havatv** [comment]
@SrNetoChan, my comments to your points.
1. Not sure what you mean here.  Do you want to change the header text of the table from "Identifier" to "Python Identifier", or would you like to include the Python identifier somewhere else than in the "Identifier" column?
2. Using ``, as @DelazJ has proposed is perhaps a solution we can agree on? I have already started to use it.
3. I think we can allow images both inside and outside of the tables - small images can be useful inside, but large illustrations are better moved outside for readability.

**Comment by SrNetoChan** [comment]
> @SrNetoChan, my comments to your points.
> 
> 1. Not sure what you mean here.  Do you want to change the header text of the table from "Identifier" to "Python Identifier", or would you like to include the Python identifier somewhere else than in the "Identifier" column?

My suggestion is to add Python identifier or Py Identifier to the header.

> 2. Using ``, as @DelazJ has proposed is perhaps a solution we can agree on? I have already started to use it.

Indeed, that is my suggestion as well.

> 3. I think we can allow images both inside and outside of the tables - small images can be useful inside, but large illustrations are better moved outside for readability.

Fine by me.

Thanks fro your work!

**Comment by SrNetoChan** [comment]
What do we do with this PR? Should we just close it? Should we add something in the writing guidelines about it?

**Comment by havatv** [comment]
@SrNetoChan, regarding 2. - does this mean that you would like us to change "Identifier" to "Python identifier" or "Py Identifier" in the table headers, or do you mean something else with "header" here?

**Comment by SrNetoChan** [comment]
> @SrNetoChan, regarding 2. - does this mean that you would like us to change "Identifier" to "Python identifier" or "Py Identifier" in the table headers, or do you mean something else with "header" here?

Changing the "Identifier" to "Python Identifier". sorry if I wasn't clear. My point is that most people won't understand that the identifier is for. Knowing that it's a python thing, they can search for it in the Python related information.

> Regarding this PR, I think we can leave it open until we have decided what format to use. Then we can close it.

Ok

**Comment by havatv** [comment]
I suggest the following simple table heading:
Label     Name    Type    Description.

We could perhaps write something about this on the first "page" of the processing algs part.

**Comment by SrNetoChan** [comment]
Closing this one, no longer needed.

**Comment by DelazJ** [comment]
It has been helpful. Thanks for initiating. and thanks to @havatv for the implementation.

**Pull request closed without merging**
