### PR TITLE
Import export bookmarks

### LINKED ISSUE #4213: [FEATURE] Add import/export bookmarks actions to browser right-click bookmarks menu
Original commit: https://github.com/qgis/QGIS/commit/4619a810e6d562b11ffe9e10e7e666eb8b262dc1 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

### PR DESCRIPTION
**Pull request by lajunek**
Goal: Users shall be able to create, import and export Spatial Bookmarks in the browser panels.

Ticket(s): fix #4213 

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by lajunek** [comment]
@DelazJ as we will brainstorm the description of the browser panel: should I merge the PR? How can I prevent the screenshot from being added to the QGIS Documentation master branch?

**Comment by lajunek** [comment]
@DelazJ brainstorm: the items in the tree can be linked to chapters where they are described already

**Comment by lajunek** [comment]
@DelazJ @havatv @SrNetoChan 
I started writing about the new browser items in QGIS testing.

My thoughts about this feature are:

- create a screenshot with only one browser panel as it is less important to show the drag and drop functionality

- mention the Project Home directory and add a link to "introduction/project_files.rst" (section "Introducing QGIS projects")

- describe the browser functionalities of bookmarks and link to "introduction/general_tools.html#spatial-bookmarks"

- ??? do we need to describe database connections in detail ???

**Comment by DelazJ** [comment]
@lajunek 
> How can I prevent the screenshot from being added to the QGIS Documentation master branch?

If you are stuck to github interface, I can see no alternative other than creating a commit with  the old screenshot:  open a master branch, copy on your disk the old screenshot, and upload it to this branch. that way, it replaced what had replaced it.
Otherwise, you can use command line to remove the commit that adds the screenshot
> the items in the tree can be linked to chapters where they are described already

Yep! the less we duplicate description, the better 
> describe the browser functionalities of bookmarks and link to "introduction/general_tools.html#spatial-bookmarks"

what about describing that in a dedicated section under the spatial bookmarks in General tools? Then we rely on the link you add in this PR to make the connection (or we update that link with the anchor of that section, if better). That way, all details about bookmarks are in a single place. It's kind of what's done for [style items management](https://docs.qgis.org/testing/en/docs/user_manual/style_library/style_manager.html#using-the-browser-panel). That being said, I did not check what are the actual bookmarks-related features in the browser.

**Comment by DelazJ** [comment]
@lajunek I suggest we merge this and push other improvements in another Pr. Thanks

**Pull request merged**
