### PR TITLE
Restructuration of the print composer overview

### PR DESCRIPTION
**Pull request by DelazJ**
Trying to tackle #648 I was unable to find where to easily and obviously add the information. This leads me trying to better structure the [overview_composer](http://docs.qgis.org/testing/en/docs/user_manual/print_composer/overview_composer.html) file. I end up with restructuring all the files in the folder (no new information added), generating two files (instead of 5 - nice for build duration): overview_composer.rst and (a new) create_output.rst.
Below is the proposed structure:
 
**Overview of the Print Composer**
 
    Sample Session
    The Composer Manager
    Menus, tools and panels of the print composer
        Tools
        Composer Menu
        Settings Menu
        Edit Menu
        View Menu
            Navigation Tools
            Hide and Show Panels
        Composition Tab
            Page size and settings
            Export settings
            Grid and guides
        Command History Tab: Revert and Restore actions
        Items Tab
**Composer Items** (didn't touch it but imho we'll need to find a way to merge some items together because there are also files with few contents - we will also gain build time)
  
     ......

**Creating an Output**

    Image export options
    SVG export options
    PDF export options
    Atlas generation
        Labels
        Data Defined Override Buttons
        Preview
        Generation

### CODE REVIEW

**Comment by yjacolin** [comment]
@DelazJ sorry too much things to review :/

**Comment by DelazJ** [comment]
@yjacolin I made no changes in the text except:
* modifying title level or inserting new title,
* |qg| and |nix| removal (and some trailing space)

This PR is really about structuring the chapter, by reorganizing the sequences of sections. So I delete some files and split their contents into the two remaining files. The new TOC is presented in my first message.
To get the new schema, I can't see how this PR could be split in different and coherent PRs: Information were partially present in each file.

**Comment by yjacolin** [comment]
I didn't mean to split the PR, just that there is too much change to really make a good review. So, please merge it. :)

**Comment by DelazJ** [comment]
ok. Merged!

**Pull request merged**
