### PR TITLE
clarify accepted image formats for plugin metadata

### PR DESCRIPTION
**Pull request by tomkralidis**
As per http://osgeo-org.1560.x6.nabble.com/plugin-metadata-txt-icon-directive-td5259046.html

### CODE REVIEW

**Comment by yjacolin** [comment]
could you break line to 80 caracters? I will merge it.

**Comment by tomkralidis** [comment]
@yjacolin any examples given the context?

**Comment by yjacolin** [comment]
Something like this:
```
icon                   False     a file name or a relative path (relative to
                                          the base folder of the plugin's compressed 
                                          package) of a web friendly image (PNG, 
                                         JPEG)
```
If you are afraid to break the build, just let it as is. I will manage this later at the next hackfest.

**Comment by tomkralidis** [comment]
Thanks @yjacolin, done.

**Comment by yjacolin** [comment]
thanks @tomkralidis

**Pull request merged**
