### PR TITLE
Blob atlas other fieldtypes

### LINKED ISSUE #4133: add feeding of layout pictures with blobs
Original commit: qgis/QGIS@ea4756ab1a26d by jef-n

### PR DESCRIPTION
**Pull request by lajunek**
Goal: Users shall be able to use a dynamic image source in the atlas

Ticket(s): fix #4133

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by lajunek** [comment]
@hatav what can I do to make html run successful?

**Comment by havatv** [comment]
> @hatav what can I do to make html run successful?

/home/runner/work/QGIS-Documentation/QGIS-Documentation/docs/user_manual/print_composer/create_output.rst:475: WARNING: image file not readable: docs/user_manual/print_composer/img/image_source.png

**Comment by lajunek** [comment]
@DelazJ I added the screenshots and corrected the name of the screenshot... HTML build and travis still have failed

**Comment by havatv** [comment]
This is the error message:

`QGIS-Documentation/QGIS-Documentation/docs/user_manual/print_composer/create_output.rst:475: WARNING: image file not readable: docs/user_manual/print_composer/img/picture_image_source.png:align:center`

A bit strange.

**Comment by lajunek** [comment]
@havatv 

> This commit does not belong to any branch on this repository.

this was the comment when committing ce5f3ce

**Comment by lajunek** [comment]
ce5f3c3

**Pull request merged**
