### PR TITLE
Adding GNU FDL to Server Guide/Manual

### PR DESCRIPTION
**Pull request by anitagraser**
Addresses https://github.com/qgis/QGIS-Documentation/issues/7116

as announced in https://lists.osgeo.org/pipermail/qgis-community-team/2021-December/005981.html

### CODE REVIEW

**Comment by anitagraser** [comment]
Looks like the failures are not related to the changes in this PR. @DelazJ do you think this is good to merge?

**Review by DelazJ — COMMENTED** [review]
Thanks @anitagraser 
The file(s) are not referenced in the existing file structure (top server `index.rst` file); they would build but not show in docs.
But I think we should do it the other way: only mention in the server intro that the document is under such license and point to the already existing license file in user manual (see eg https://github.com/qgis/QGIS-Documentation/pull/6923/files)
One day, we should consider moving that appendices folder out of the user_manual doc, to a generic document that would contain info that are not strictly about a single doc (documentation presentation, translation/contribution page, appendices, contents in #7178 until website refactoring, ...)

**Comment by DelazJ** [comment]
@elpaso I noticed in #6923 that the license is gnu fdl >=1.2. The [user manual license](file:///media/delazj/TRAVAIL/dev/github/QGIS-Documentation/build/html/en/docs/user_manual/preamble/preamble.html) is gnu fdl >=1.3. The [appendix B](https://docs.qgis.org/testing/en/docs/user_manual/appendices/GNU_FDL.html#gfl-appendix) is gnu_fdl 1.3. Would that harm anyone if cookbook is raised to gnu_fdl>=1.3, in order to have things harmonized and refer to the same (version) license?

**Comment by anitagraser** [comment]
> and point to the already existing license file in user manual

That would be fine too, sure.

**Comment by anitagraser** [comment]
@elpaso Are you ok with updating the cookbook license to FDL>= 1.3 so we can have one consistent license statement?

**Comment by DelazJ** [comment]
Maybe something you could quickly discuss at the next PSC meeting (tuesday if i'm not wrong)?

**Comment by anitagraser** [comment]
@DelazJ Yes, I've added it to the agenda. Thanks.

**Comment by elpaso** [comment]
> @elpaso Are you ok with updating the cookbook license to FDL>= 1.3 so we can have one consistent license statement?

@anitagraser I see no problems with updating, let's do it.

**Comment by DelazJ** [comment]
Superseded by #7338

**Pull request closed without merging**
