### PR TITLE
Fix pdf creation

### PR DESCRIPTION
**Pull request by SrNetoChan**
Goal:
- Separate PDF creation from HTML, allowing it to fail without risking HTML build
- Make Latex less verbose and ignore errors

Ticket(s): #

- [x] Backport to LTR documentation is required

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Let's pull and see what happens :-)

**Comment by DelazJ** [comment]
> Separate PDF creation from HTML, allowing it to **fail** without risking HTML build

Any particular issue concerned?

**Comment by SrNetoChan** [comment]
> > Separate PDF creation from HTML, allowing it to **fail** without risking HTML build
> 
> Any particular issue concerned?

@DelazJ the PDF creation was failing for japanese, and the way the makefile was, that would break the all HTML build.

@rduivenvoorde had to comment pdf creation for 3.10 release.

The idea is to make sure HTML jobs are finished and synched before even try to build the PDFs

Later I will try to fix the PDFs for ja

**Comment by DelazJ** [comment]
Ok. Thanks to you.

**Pull request merged**
