### PR TITLE
Indentation and trailing spaces fixes

### PR DESCRIPTION
**Pull request by DelazJ**
\+ some mismatch of data types list and table headers

### CODE REVIEW

**Comment by havatv** [comment]
Could we wait with this one until #4734 (and #4733) is merged?

**Comment by DelazJ** [comment]
yep, no problem @havatv. But meanwhile could you fix the spacing in the new algs you add there? Thanks

**Comment by havatv** [comment]
> yep, no problem @havatv. But meanwhile could you fix the spacing in the new algs you add there? Thanks

I have tried. Will have a second look - hopefully tomorrow.

**Comment by havatv** [comment]
Thanks for fixing this, @DelazJ!

**Pull request merged**
