### PR TITLE
Move the Developers Guide to the doc repository

### PR DESCRIPTION
**Pull request by DelazJ**
As discussed in #1566 this PR begins the move.
It actually simply move the Developers Guide chapter and generates its pdf doc (given that the Cookbook has a PDF version, I thought it could be applied to dev guide even though documentation guidelines is not in pdf - not sure what are the rules of pdf*ing*)

The structure of the folder is kept as is. Maybe should we reorganize it to separate general rules from particular areas of coding (authentication, server...)
dev_guide

### Some limits

* The GRASS chapter didn't move as I still have questions about it. See qgis/QGIS-Website#406
* **Translation**: creating a new document in the master branch makes it available in Testing release (hence, not translatable until next doc publication). Not sure it's a good thing to lose translations like this.
A fix could be a backport to 2.14 branch for translation: of course only backport stuffs that are applicable to 2.14 (e.g., not sure about ogc conformance) .

@rduivenvoorde @SrNetoChan @yjacolin

### CODE REVIEW

**Comment by yjacolin** [comment]
If it easy to migrate translation, you can try but imho this is too much work. Maybe transifex will find the last translation and will do some suggestion.

**Comment by DelazJ** [comment]
Of course integrating translations in the PR is a no go. Those are managed in Transifex and yes they'll be broken but Transifex will still propose the corresponding translation. And someone will have to reapply them, which I've been said, is not a hard task.
So, does a backport to 2.14 sound like an understandable way to go?

Remains the GRASS chapter future...

**Comment by yjacolin** [comment]
As said early last year: if you want to manage backport, just do it :)

Some though: it will break the translation which is not great but manageable, translation is definitively not the bottleneck. Another point of view: does this kind of change could be see as "new feature" and not a small fix? And third point of view, if you removed it from the website, that's meant that this doc disappeared so it will be good to have it again in the documentation :)

All in all, backport is probably the way to go related to the third point.

**Comment by SrNetoChan** [comment]
@DelazJ @yjacolin I think we should merge this into the documentation as soon as possible. I don't think we need to backport it to 2.14; we can just keep all this information on the website until the next documentation release (2.18 if it goes LTR). Meanwhile, we can start working on this new section and integrate other ideas around development documentation that makes no sense to put on the website. Like Nyall's proposal of a good PR https://github.com/qgis/QGIS/pull/3919. In boundless we also want to contribute to this new section with instructions on to develop on top of QGIS both in Python and C++.

The sooner we have it in the testing documentation, the sooner we can add more information to it.

**Comment by SrNetoChan** [comment]
Thanks!

**Comment by yjacolin** [comment]
Probably you don't need anymore my opinion, but for the record: +1

Y.

**Comment by DelazJ** [comment]
@yjacolin sorry I didn't want to bypass you. Due to your approval of this PR a month ago I concluded that you were ok to have it merged (and it looks like I was right :)) , reason why I rebased and merged it when @SrNetoChan asked for it.

**Comment by yjacolin** [comment]
No problem I just wanted to reply to "the ping" ;)

Le 5 mars 2017 2:00 PM, "Harrissou Sant-anna" <notifications@github.com> a
écrit :

**Comment by dakcarto** [comment]
@SrNetoChan @DelazJ @yjacolin thanks to everyone on the docs team for working on this! Much appreciated.

**Pull request merged**
