### PR TITLE
Use bot with PAT to update statistics

### PR DESCRIPTION
**Pull request by m-kuhn**
PAT only valid for a year, it's not possible to create a longer one

Goal:

Ticket(s): #

- [ ] Backport to LTR documentation is requested

### CODE REVIEW

**Comment by DelazJ** [comment]
@m-kuhn I have no expertise here, so if it is good with you then I'm also OK

**Comment by DelazJ** [comment]
@m-kuhn sorry but looks like we need to give some permission to geo-ninja (https://github.com/qgis/QGIS-Documentation/actions/runs/5864142163/job/15898729281#step:8:533)

**Comment by m-kuhn** [comment]
Probably the _`GH_PAT` does not have sufficient permissions.
I'll need @3nids to fix it

**Comment by geo-ninja** [comment]
I updated the permissions, can you try again?

**Comment by m-kuhn** [comment]
Thank you @geo-ninja
Looks like we still have some limitations though


```
  remote: Permission to geo-ninja/QGIS-Documentation.git denied to geo-ninja.
  fatal: unable to access 'https://github.com/geo-ninja/QGIS-Documentation/': The requested URL returned error: 403
```

**Comment by DelazJ** [comment]
Hi,
I forgot to report but the action is still failing
https://github.com/qgis/QGIS-Documentation/actions/runs/6080809961/job/16495355349#step:8:535
>   ! [remote rejected]     create-pull-request/patch -> create-pull-request/patch (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/auto-label.yml` without `workflow` scope)

Seems that the PAT still has permission limitations. Thanks.

**Pull request merged**
