### PR TITLE
"File" menu is "Project" in 2.8

### PR DESCRIPTION
**Pull request by stragu**
Does this automatically get pushed to Master if accepted in manual_en_v2.8 branch ?

### CODE REVIEW

**Comment by yjacolin** [comment]
No you should create a new PR for master.

**Comment by stragu** [comment]
Thanks. I guess I'd have to check if it is also the case in the current dev branch before doing that then.

**Comment by yjacolin** [comment]
@stragu I confirm that there is a "Project" menu in master ;)

checkvalidity_layer_error1

**Comment by stragu** [comment]
@yjacolin All good, it had been fixed a while ago in Master: https://github.com/qgis/QGIS-Documentation/commit/71296575ea43c0ba3a187373de47d9257c5f4e21

Cheers!

**Pull request merged**
