### PR TITLE
[pyqgis] add a small QgsSpatialIndexKDBush description

### LINKED ISSUE #2775: [FEATURE] QgsSpatialIndexKDBush
Original commit: https://github.com/qgis/QGIS/commit/0df1056dd4fd7d4d86118c8d2d2b1963917afbb9 by nyalldawson

A very fast static spatial index for 2D points based on a flat KD-tree,
using https://github.com/mourner/kdbush.hpp

Compared to QgsSpatialIndex, this index:
 - supports single point features only (no multipoints)
 - is static (features cannot be added or removed from the index after construction)
 - is much faster!
 - supports true "distance based" searches, i.e. return all points within a radius
from a search point

### PR DESCRIPTION
**Pull request by ghtmtt**
Goal: small description (to get people aware of the existence) of  `QgsSpatialIndexKDBush`, no code snippet provided and the description is taken from the API. 

@Gustry if it is still in your to do list and you want to add a specific example then go :D

Ticket(s): fix #2775

- [x] Backport to LTR documentation is required

### CODE REVIEW

**Comment by ghtmtt** [comment]
I restarted Travis and finally we have green light! @DelazJ can I merge this?

**Comment by ghtmtt** [comment]
@DelazJ can I merge this?

**Comment by DelazJ** [comment]
Sorry for the late reply.
I hoped we'd get an example but... Please do. Thanks.

**Comment by ghtmtt** [comment]
thanks @DelazJ

**Pull request merged**
