### PR TITLE
Describe some Attribute form options

### LINKED ISSUE #2132: [FEATURE] Default values on update
Original commit: https://github.com/qgis/QGIS/commit/08cb2d78d3be51e951e40f1bee80dc6209c34f64 by m-kuhn

Add an option to add default values on update of attributes or geometry.
This can be seen as a "derived value" that will be saved to the database
(like area of a polygon) or as a means to track last_modified dates etc.

See #5218

### PR DESCRIPTION
**Pull request by DelazJ**
Fixes #2132 and address a not reported dialog refactoring

### CODE REVIEW

**Comment by DelazJ** [comment]
Can't find what makes Travis unhappy here. afaics, the *vector_expressions* label in L1952 does exist at https://github.com/qgis/QGIS-Documentation/blame/master/source/docs/user_manual/working_with_vector/expression.rst#L7
Any idea?

**Comment by ghtmtt** [comment]
no idea.. did you have problems also in local building?

**Comment by yjacolin** [comment]
Yes, rebase from master ;) @DelazJ you gave the master url instead of the one in the PR: https://github.com/DelazJ/QGIS-Documentation/blame/b7d372ffa4b8fa97623d06cf0f6188ba1c8afd46/source/docs/user_manual/working_with_vector/vector_properties.rst#L5
currently, in this PR, the label is:
```
.. _vector_properties_dialog:
```

**Comment by DelazJ** [comment]
@ghtmtt I did not try local building. I had trouble last time with the recipe and did not waste time trying to figure out.
@yjacolin here's the Travis message
> Warning, treated as error:
/home/travis/build/qgis/QGIS-Documentation/source/docs/user_manual/working_with_vector/vector_properties.rst:1951:undefined label: identify results (if the link has no caption the label must precede a section header)
make: *** [html] Error 1

So I understand that there's something wrong in my commit, line 1951. There, I'm referring to an anchor *vector_expressions* which is the one I linked in my first message and exists. Not sure I understand your link.

**Comment by yjacolin** [comment]
wrong file :( sorry

**Pull request merged**
