### PR TITLE
Describe the "planimetric measurements" option

### PR DESCRIPTION
**Pull request by DelazJ**
refs https://github.com/qgis/QGIS/pull/30952 (no report in this repo nor in changelog - I came across this writing #4694 )

@nyalldawson @m-kuhn I would appreciate your review here since I'm not sure I understand the purpose, neither from your discussion in the implementation PR nor through my testing (which led to https://github.com/qgis/QGIS/issues/33528). Maybe did I miss some key points?

### CODE REVIEW

**Comment by DelazJ** [comment]
>  havatv approved these changes

@havatv does it mean that you checked the feature/PR and the description is conform?

**Comment by havatv** [comment]
I did not check, but the description looked logical to me.  Perhaps we should wait for input from developers.

**Comment by DelazJ** [comment]
I'd prefer, indeed

**Comment by m-kuhn** [comment]
I would just write this:

*This sets the default for the "planimetric measurements" property for newly created projects.*

and link to a more descriptive explanation in the project properties (or another suitable place?) section. This way we will have one single place to explain the planimetric option.

**Comment by DelazJ** [comment]
Done @m-kuhn 
Did you see https://github.com/qgis/QGIS/issues/33528?

**Pull request merged**
