### PR TITLE
Referenced tutorials

### PR DESCRIPTION
**Pull request by jakobmiksch**
The tutorials of the QGIS trainings manual (https://docs.qgis.org/2.18/en/docs/training_manual/create_vector_data/forms.html#ls-forms) were not referenced before.

Could you please check if I referenced the tutorials correctly (according to Sphinx) ?

### CODE REVIEW

**Comment by DelazJ** [comment]
You first need to place an anchor at the place you want to reference. Please see http://docs.qgis.org/2.18/en/docs/documentation_guidelines/writing.html#label-reference

**Comment by DelazJ** [comment]
@bufferclip are you still on this pr? Need some help?

**Comment by bufferclip** [comment]
thanks for the reminder, I have not worked on it anymore. I will try to do it soon, but everyone is welcome to take over

**Comment by jakobmiksch** [comment]
@DelazJ Thanks for finishing this

**Pull request merged**
