### PR TITLE
[server] Add NO_MTEXT and FORCE_2D dxf export parameters

### PR DESCRIPTION
**Pull request by m-kuhn**
Only available starting from QGIS 3.12

### CODE REVIEW

**Comment by havatv** [comment]
Since this is a 3.12 feature, the merged has to be delayed until 3.10 has become the LTR.

**Comment by m-kuhn** [comment]
No worries, just merge whenever you feel comfortable.
So the branching/release of the 3.10 docs is planned for 21.2.2020?

**Comment by havatv** [comment]
> No worries, just merge whenever you feel comfortable.
> So the branching/release of the 3.10 docs is planned for 21.2.2020?

I don't know, but I guess it will happen when 3.10 becomes LTR (21.2.2020).

**Comment by DelazJ** [comment]
Yes, that's the plan. An announce/proposal that neither got much attention as i wished at http://qgis-community-team.2324516.n4.nabble.com/Qgis-community-team-Releasing-QGIS-3-10-doc-when-3-10-quot-becomes-quot-LTR-fev-2020-td3121.html

**Comment by DelazJ** [comment]
Plan has changed, 3.12 features can be merged now. No need to wait for LTR release

**Pull request merged**
