### PR TITLE
Replace the sphinx image role with figure's

### PR DESCRIPTION
**Pull request by DelazJ**
This PR replaces all the `.. image::` calls in the docs with `.. figure::`.
Why? It was heavily suggested in #3142.
What does it improve? I'm not really sure. I thought this is what made the images in the [gentle introduction chapter](https://docs.qgis.org/testing/en/docs/gentle_gis_introduction/index.html) clickable, interactive (then more visible, a property it could be nice to add to some training manual screenshots) but it looks like it's due to the use of the `:width:` option (changes not on my todo list). Anyway, at least it harmonizes the way screenshots were referenced.
Also it updates the instructions regarding figure addition and referencing substitutions for GitHub preview

### CODE REVIEW

**Comment by havatv** [comment]
This looks sensible to me.

**Comment by havatv** [comment]
Figures can float around, while images will not float around, so I think figures need to have captions.
See the PDF for the user manual, where four illustrations for the digitizing properties section (12.2.18) have floated to the start of the Expressions section (12.3).

**Comment by DelazJ** [comment]
@havatv Not sure I fully get your point but should we not instead keep using `.. image::`? Giving a look to many pages in the training manual in PDF, screenshots are rather well placed (we often use `.. image::` there) and I understand that using `.. figure::` could misplace them. On the other hand, the user manual is full of `.. figure::` and screenshots are often not at their expected place.

**Comment by havatv** [comment]
What I mean is that we need to know how `.. image` and `.. figure` work.  And since figures can float around, they should have captions (and they should preferably be referenced from the text with their figure number, but I have not checked how easy that is with rst).

**Comment by DelazJ** [comment]
> What I mean is that we need to know how .. image and .. figure work.

Agreed. And this was my concern with the `What does it improve?` in my initial comment.
> And since figures can float around, they should have captions (and they should preferably be referenced from the text with their figure number, but I have not checked how easy that is to achieve with rst).

In the PDF (where actually the issue of misplacement arises) the figure number is assigned incrementally (using [numfig](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-numfig) variable), as figures are generated so you can not guess a long-term figure number (may be worth digging the numref role route though).
Currently we use anchors for those figures so that they can be referenced if needed. But I'm not convinced that, despite they may be misplaced (note: `a misplaced figure today can be well placed after few commits - it's a matter of space on the paper`), we need to reference all the figures in the text. From memories, we already do it at some places, when the screenshot is far from the description e.g.).

**Comment by DelazJ** [comment]
I'm not really convinced by the rightness of this pull request.

**Comment by havatv** [comment]
One advantage of using `.. figure` is that a caption can be added (with an automatic figure number for PDFs).  Another is that elements coded with `.. figure` float, making nice PDF rendering easier.  There are also some other possibilities with them, compared to elements coded with `.. image` (see for instance http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure).

**Comment by DelazJ** [comment]
I removed the replacement section from this PR as it can be  handled separately.
> see for instance http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure

Yes, I know that link but since I can't find docs on `image`, hard for me to say what are image properties/limitations, hence what figure can do better or not.
Also, I think captions are good (though not particularly appropriate or a bit boring in the training manual case) but I don't consider the images floating as an advantage. You never know where the figure will be placed so if we move on with figures, adding caption would necessarily be a prerequisite (not on my todo list before a moment).

**Comment by DelazJ** [comment]
Closing this (for the moment?)

**Pull request closed without merging**
