### PR TITLE
getMap in dxf format #611

### PR DESCRIPTION
**Pull request by yjacolin**
This is more a cleanup commit than an integration of the feature.

### CODE REVIEW

**Comment by DelazJ** [comment]
LGTM considering my remarks in #1059

**Comment by yjacolin** [comment]
Please wait to merge after #1059

**Comment by DelazJ** [comment]
no worry nor hurry. I was planning to let you merge yourself :)

**Comment by yjacolin** [comment]
it could be also a note for myself ;), anyway for the one who will merge it :)

**Pull request merged**
