### PR TITLE
Update screenshots - introduction

### PR DESCRIPTION
**Pull request by havatv**
Goal: QGIS 3 updates. The ones that I found in most need of updating.

Ticket(s): #2441

- [ ] Backport to LTR documentation is required

### CODE REVIEW

**Comment by havatv** [comment]
Fairly simple update (screenshots with QGIS 3.10.1 only). There should not be a need for review here, so if there are no objections, I will merge soon.

**Comment by DelazJ** [comment]
@havatv are you sure the recent colors screenshot is of 3.10? "Select color" dialogs should now have at least a help button, and (I think it's default) a "new layer colors" in the drop-down menu

**Comment by havatv** [comment]
> @havatv are you sure the recent colors screenshot is of 3.10? "Select color" dialogs should now have at least a help button, and (I think it's default) a "new layer colors" in the drop-down menu

This was very strange.  I did the screenshot in 3.10.1 yesterday, but for some reason the uploaded image was identical to the old one.  I have tried to fix now.  Can you check if it is OK?

**Comment by havatv** [comment]
I tried to upload once again, and apparently it succeeds (github says that the file was updated some seconds ago), but the image stayed the same.  I then removed the existing file and uploaded again, and now it seems to have worked.  Very strange.

**Comment by havatv** [comment]
Thanks, @DelazJ!

**Pull request merged**
