### PR TITLE
Add note about using pyrcc4 on Windows

### PR DESCRIPTION
**Pull request by 3XE**
Can save headaches for those using Command Prompt/Powershell when they try to run it and discover it is not in PATH.  Not that I would do such a thing ;)

### CODE REVIEW

**Comment by yjacolin** [comment]
Thank for you PR, could you add more information (ie your pr comment gives more information than in the changes you send :) )

```Something like: Using Command Prompt/Powershell pyrcc4 is not in the path so you can have some trouble. Please use OSGeo4W Shell ....```

Any though?

**Comment by 3XE** [comment]
No problem, have added more detail in commit f5ad861

**Comment by yjacolin** [comment]
Sorry for this comment, but could you limit your line to 80 letters?

I will merge your PR right away after.

**Comment by 3XE** [comment]
Yes, of course, my mistake.  Done in commit 5dca2e8.

Thanks :)

**Comment by yjacolin** [comment]
thanks! :)

**Pull request merged**
