### PR TITLE
Remove mention of obsolete use of |updatedisclaimer

### PR DESCRIPTION
**Pull request by DelazJ**
### Description

The file used as example no longer exists but, at least let's not mislead people on the |updatedisclaimer| usage

Ticket: see https://docs.qgis.org/3.4/en/docs/documentation_guidelines/do_translations.html#translate-a-file

- [x] Backport to LTR documentation is required

### Minimal requirements for merging *(for maintainers)*

- [x] The description of this PR is coherent with the manual and does not provide wrong information.
- [x] This PR passes the checks.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
That makes sense. Although, yes documentation translation will be a moving target... But even if we used the disclaimer, there's no way we could guarantee that no changes would land in a particular file. I hope translators don't get too angry with us.

Looks good to merge.

**Comment by DelazJ** [comment]
Translators should not be affected imo.
The fact is that the |updatedisclaimer| is available only in master not in released branch hence translatable versions (its removal is part of the cleanup work required for new release). So translators will likely never find this expression, and in the current process, they just have to pick among the files transifex provides, not pick their own file/branch.

When/If we make the guidelines independant from release, I think using that tag would neither make sense, because these docs are assumed to be finished. until...

**Comment by SrNetoChan** [comment]
Looks good to merge. Feel free to do it.

**Comment by SrNetoChan** [comment]
And yes, you are right, translators will never see a disclaimer.

**Pull request merged**
