### PR TITLE
Add figure for Vertex editor

### PR DESCRIPTION
**Pull request by SrNetoChan**

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@DelazJ I wanted to create an example with Z and M, but I was not able to create a layer with it. Is this ok for now?

**Comment by yjacolin** [comment]
A general question: do you think it is a good way to add a number in the reference for figure?

**Comment by SrNetoChan** [comment]
It's very strange to have to change all figure's number whenever we add a new one. Maybe there is a better way to do it. Another thing to add to the hackfest discussion.

**Comment by DelazJ** [comment]
@SrNetoChan No problem with Z or M, I'm fine with this. Thanks. LGTM

**Pull request merged**
