### PR TITLE
Move Print composer chapter

### PR DESCRIPTION
**Pull request by DelazJ**
Move the print composer chapter after the Raster one...

### CODE REVIEW

**Comment by yjacolin** [comment]
why? I think that all `working_with_XXX` chapter should be grouped at the same location and should not be broken with somethin else. Though? Could we pu this after `working_with_gps/index`? What are others opinion?

**Comment by DelazJ** [comment]
The goal is to place it close to layers that are used in a layout, as discussed in the user ML.
I hesitated to place it after "Working with OGC" and looking at it again, thinks it could be there also, despite a big part of this chapter is about configuring server.
But, i'm not in favor of putting it after "working with GPS data". This chapter is about configuring gps and the use of the gps core plugin and has definitely nothing to do with print composer nor the other chapters (except "working with" in the title) imho. I even wonder if this chapter shouldn't move under plugins chapter (and if plugins chapter shouldn't be before Processing matters)...

**Comment by DelazJ** [comment]
Any other opinion?

**Comment by SrNetoChan** [comment]
I agree with this change. Print composer makes much more sense after loading layers. I would prefer your origin proposal, but I'm also ok if it goes after Working with OGC as the QGIS as OSC client describes how to load OGC layers.

Working with GPS, have nothing to do with the other two sections, apart from the name.

**Comment by DelazJ** [comment]
Merging this. We'll see later what it gives with the "Supported data..." chapter refactoring

**Pull request merged**
