### PR TITLE
link updated in R Scripts Processing

### PR DESCRIPTION
**Pull request by ghtmtt**
super small change in link at the top of the page, can be merged without problems

### CODE REVIEW

**Comment by DelazJ** [comment]
Just out of curiosity, why does this link change so often? If I recall well, it might be the third or fourth time you change it.

**Comment by ghtmtt** [comment]
You are right and I'm really sorry. 
We had some problem to find out what project of the University pays for these features. And I get wrong information. These time I spoke directly with the boss, so this should be the last time

**Comment by yjacolin** [comment]
@ghtmtt I thought about this kind of reason :) I merged it.

**Comment by ghtmtt** [comment]
Thanks @yjacolin

**Comment by DelazJ** [comment]
@ghtmtt Never mind. It was just my curiosity. Given that the doc is not yet being translated, your changes disturbs nobody. :)

**Pull request merged**
